--------------------------------------------------------
--  Arquivo criado - Ter�a-feira-Junho-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CEIS_ORGAO
--------------------------------------------------------

  CREATE TABLE "CEIS_ORGAO" 
   (	"ORGAO" VARCHAR2(512 BYTE), 
	"UF" VARCHAR2(50 BYTE), 
	"COMPLEMENTO" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CEIS_SANCAO
--------------------------------------------------------

  CREATE TABLE "CEIS_SANCAO" 
   (	"TIPO" VARCHAR2(255 BYTE), 
	"CNPJ_CPF_SANCIONADO" VARCHAR2(30 BYTE), 
	"NOME_ORGAO" VARCHAR2(512 BYTE), 
	"NUMERO_PROCESSO" VARCHAR2(255 BYTE), 
	"DATA_INICIO" DATE, 
	"DATA_FINAL" DATE, 
	"DATA_PUBLICACAO" DATE, 
	"PUBLICACAO" VARCHAR2(255 BYTE), 
	"DETALHAMENTO" VARCHAR2(2048 BYTE), 
	"ABRANGENCIA" VARCHAR2(255 BYTE), 
	"FUNDAMENTACAO_LEGAL" VARCHAR2(255 BYTE), 
	"DESCRICAO_FUNDAMENTACAO" VARCHAR2(3000 BYTE), 
	"OBSERVACOES" VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CEIS_SANCIONADO
--------------------------------------------------------

  CREATE TABLE "CEIS_SANCIONADO" 
   (	"CNPJ_CPF" VARCHAR2(30 BYTE), 
	"NOME_RAZAO_SOCIAL" VARCHAR2(255 BYTE), 
	"NOME_FANTASIA" VARCHAR2(255 BYTE), 
	"TIPO_PESSOA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Materialized View CEI_INADIMPLENTE_MAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "CEI_INADIMPLENTE_MAT" ("CNPJ_CPF")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT 
    CNPJ_CPF 
FROM 
    UFC2.CEI_INADIMPLENTE_MAT@UFC.SEFAZ.MA.GOV.BR
WHERE NUMERO_DOCUMENTO IS NOT NULL;

  CREATE UNIQUE INDEX "CEI_INADIMPLENTE_MAT_INDEX1" ON "CEI_INADIMPLENTE_MAT" ("CNPJ_CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON MATERIALIZED VIEW "CEI_INADIMPLENTE_MAT"  IS 'snapshot table for snapshot UFC_SEM.CEI_INADIMPLENTE_MAT';
