
  CREATE MATERIALIZED VIEW "UFC_SEM"."SAMEAS_CAD_RFB_EMPRESA" ("RFB_ID", "CAD_ID")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/1440
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT rfb.CNPJ_RAIZ AS RFB_ID, cad.ID AS CAD_ID 
            FROM "RFB_EMPRESA" rfb
            INNER JOIN
            "CAD_EMPRESA" cad
            ON
            rfb.CNPJ_RAIZ = cad.CNPJ_RAIZ;

  CREATE INDEX "UFC_SEM"."SAMEAS_CAD_RFB_EMPRESA_INDEX1" ON "UFC_SEM"."SAMEAS_CAD_RFB_EMPRESA" ("RFB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "UFC_SEM"."SAMEAS_CAD_RFB_EMPRESA_INDEX2" ON "UFC_SEM"."SAMEAS_CAD_RFB_EMPRESA" ("CAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."SAMEAS_CAD_RFB_EMPRESA"  IS 'snapshot table for snapshot SAMEAS_CAD_RFB_EMPRESA';
