--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Setembro-30-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IBGE_MESORREGIAO
--------------------------------------------------------

  CREATE TABLE "IBGE_MESORREGIAO" 
   (	"ID_MESORREGIAO" VARCHAR2(100 BYTE), 
	"CODIGO_MESORREGIAO" NUMBER(*,0), 
	"NOME_MESORREGIAO" VARCHAR2(100 BYTE), 
	"ID_UF" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_MICRORREGIAO
--------------------------------------------------------

  CREATE TABLE "IBGE_MICRORREGIAO" 
   (	"ID_MICRORREGIAO" VARCHAR2(100 BYTE), 
	"CODIGO_MICRORREGIAO" NUMBER(*,0), 
	"NOME_MICRORREGIAO" VARCHAR2(100 BYTE), 
	"ID_MESORREGIAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_MUNICIPIO
--------------------------------------------------------

  CREATE TABLE "IBGE_MUNICIPIO" 
   (	"ID_MUNICIPIO" VARCHAR2(100 BYTE), 
	"CODIGO_MUNICIPIO" NUMBER(*,0), 
	"CODIGO_MUNICIPIO_COMPLETO" NUMBER(*,0), 
	"NOME_MUNICIPIO" VARCHAR2(100 BYTE), 
	"ID_MICRORREGIAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_PAIS
--------------------------------------------------------

  CREATE TABLE "IBGE_PAIS" 
   (	"ID_PAIS" VARCHAR2(100 BYTE), 
	"CODIGO_PAIS" NUMBER(*,0), 
	"NOME_PAIS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  --------------------------------------------------------
--  DDL for Table IBGE_UNIDADE_FEDERATIVA
--------------------------------------------------------

  CREATE TABLE "IBGE_UNIDADE_FEDERATIVA" 
   (	"ID_UF" VARCHAR2(100 BYTE), 
	"SIGLA_UF" VARCHAR2(100 BYTE), 
	"NOME_UF" VARCHAR2(100 BYTE), 
	"CODIGO_IBGE" NUMBER(*,0), 
	"ID_PAIS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index IBGE_MESORREGIAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBGE_MESORREGIAO_PK" ON "IBGE_MESORREGIAO" ("ID_MESORREGIAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index IBGE_MICRORREGIAO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBGE_MICRORREGIAO_PK" ON "IBGE_MICRORREGIAO" ("ID_MICRORREGIAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index IBGE_MUNICIPIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBGE_MUNICIPIO_PK" ON "IBGE_MUNICIPIO" ("ID_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index IBGE_PAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBGE_PAIS_PK" ON "IBGE_PAIS" ("ID_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index IBGE_UNIDADE_FEDERATIVA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBGE_UNIDADE_FEDERATIVA_PK" ON "IBGE_UNIDADE_FEDERATIVA" ("ID_UF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  --------------------------------------------------------
--  Constraints for Table IBGE_MESORREGIAO
--------------------------------------------------------

  ALTER TABLE "IBGE_MESORREGIAO" ADD CONSTRAINT "IBGE_MESORREGIAO_PK" PRIMARY KEY ("ID_MESORREGIAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_MESORREGIAO" MODIFY ("ID_MESORREGIAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MESORREGIAO" MODIFY ("CODIGO_MESORREGIAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MESORREGIAO" MODIFY ("NOME_MESORREGIAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MESORREGIAO" MODIFY ("ID_UF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_MICRORREGIAO
--------------------------------------------------------

  ALTER TABLE "IBGE_MICRORREGIAO" ADD CONSTRAINT "IBGE_MICRORREGIAO_PK" PRIMARY KEY ("ID_MICRORREGIAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_MICRORREGIAO" MODIFY ("ID_MICRORREGIAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MICRORREGIAO" MODIFY ("CODIGO_MICRORREGIAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MICRORREGIAO" MODIFY ("NOME_MICRORREGIAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MICRORREGIAO" MODIFY ("ID_MESORREGIAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_MUNICIPIO
--------------------------------------------------------

  ALTER TABLE "IBGE_MUNICIPIO" ADD CONSTRAINT "IBGE_MUNICIPIO_PK" PRIMARY KEY ("ID_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_MUNICIPIO" MODIFY ("ID_MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MUNICIPIO" MODIFY ("CODIGO_MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MUNICIPIO" MODIFY ("CODIGO_MUNICIPIO_COMPLETO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MUNICIPIO" MODIFY ("NOME_MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_MUNICIPIO" MODIFY ("ID_MICRORREGIAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_PAIS
--------------------------------------------------------

  ALTER TABLE "IBGE_PAIS" ADD CONSTRAINT "IBGE_PAIS_PK" PRIMARY KEY ("ID_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_PAIS" MODIFY ("ID_PAIS" NOT NULL ENABLE);
  ALTER TABLE "IBGE_PAIS" MODIFY ("CODIGO_PAIS" NOT NULL ENABLE);
  ALTER TABLE "IBGE_PAIS" MODIFY ("NOME_PAIS" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table IBGE_UNIDADE_FEDERATIVA
--------------------------------------------------------

  ALTER TABLE "IBGE_UNIDADE_FEDERATIVA" ADD CONSTRAINT "IBGE_UNIDADE_FEDERATIVA_PK" PRIMARY KEY ("ID_UF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_UNIDADE_FEDERATIVA" MODIFY ("ID_UF" NOT NULL ENABLE);
  ALTER TABLE "IBGE_UNIDADE_FEDERATIVA" MODIFY ("SIGLA_UF" NOT NULL ENABLE);
  ALTER TABLE "IBGE_UNIDADE_FEDERATIVA" MODIFY ("NOME_UF" NOT NULL ENABLE);
  ALTER TABLE "IBGE_UNIDADE_FEDERATIVA" MODIFY ("CODIGO_IBGE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_UNIDADE_FEDERATIVA" MODIFY ("ID_PAIS" NOT NULL ENABLE);

 --------------------------------------------------------
--  Ref Constraints for Table IBGE_MESORREGIAO
--------------------------------------------------------

  ALTER TABLE "IBGE_MESORREGIAO" ADD CONSTRAINT "IBGE_MESORREGIAO_FK1" FOREIGN KEY ("ID_UF")
	  REFERENCES "IBGE_UNIDADE_FEDERATIVA" ("ID_UF") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_MICRORREGIAO
--------------------------------------------------------

  ALTER TABLE "IBGE_MICRORREGIAO" ADD CONSTRAINT "IBGE_MICRORREGIAO_FK1" FOREIGN KEY ("ID_MESORREGIAO")
	  REFERENCES "IBGE_MESORREGIAO" ("ID_MESORREGIAO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_MUNICIPIO
--------------------------------------------------------

  ALTER TABLE "IBGE_MUNICIPIO" ADD CONSTRAINT "IBGE_MUNICIPIO_FK1" FOREIGN KEY ("ID_MICRORREGIAO")
	  REFERENCES "IBGE_MICRORREGIAO" ("ID_MICRORREGIAO") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table IBGE_UNIDADE_FEDERATIVA
--------------------------------------------------------

  ALTER TABLE "IBGE_UNIDADE_FEDERATIVA" ADD CONSTRAINT "IBGE_UNIDADE_FEDERATIVA_FK1" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "IBGE_PAIS" ("ID_PAIS") ON DELETE CASCADE ENABLE;
