--------------------------------------------------------
--  Arquivo criado - Terça-feira-Junho-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View CEI_INADIMPLENCIA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UFC_SEM"."CEI_INADIMPLENCIA" ("CODIGO", "CODIGO_INFRACAO", "TIPO_INFRACAO", "VALOR_OBRIGACAO", "OBJETO_OBRIGACAO", "DATA_VENCIMENTO_OBRIGACAO", "DATA_INICIAL", "NUM_MESES", "OBSERVACAO", "DATA_EXCLUSAO", "DATA_INCLUSAO", "MOTIVO_EXCLUSAO", "UNIDADE_INCLUSAO", "USUARIO_INCLUSAO", "USUARIO_EXCLUSAO", "CNPJ_CPF_INADIMPLENTE") AS 
  (

    SELECT "CODIGO","CODIGO_INFRACAO","TIPO_INFRACAO","VALOR_OBRIGACAO","OBJETO_OBRIGACAO","DATA_VENCIMENTO_OBRIGACAO","DATA_INICIAL","NUM_MESES","OBSERVACAO","DATA_EXCLUSAO","DATA_INCLUSAO","MOTIVO_EXCLUSAO","UNIDADE_INCLUSAO","USUARIO_INCLUSAO","USUARIO_EXCLUSAO","CNPJ_CPF_INADIMPLENTE" FROM CEI_INADIMPLENCIA@UFC
)
WITH READ ONLY
;
--------------------------------------------------------
--  DDL for View CEI_INADIMPLENTE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UFC_SEM"."CEI_INADIMPLENTE" ("CNPJ_CPF", "NUMERO_DOCUMENTO") AS 
  (
    SELECT "CNPJ_CPF","NUMERO_DOCUMENTO" FROM CEI_INADIMPLENTE@UFC
   )
WITH READ ONLY
;
--------------------------------------------------------
--  DDL for Materialized View CEI_INADIMPLENTE_MAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."CEI_INADIMPLENTE_MAT" ("CNPJ_CPF")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT 
    CNPJ_CPF 
FROM 
    UFC2.CEI_INADIMPLENTE_MAT@UFC.SEFAZ.MA.GOV.BR
WHERE NUMERO_DOCUMENTO IS NOT NULL;

  CREATE UNIQUE INDEX "UFC_SEM"."CEI_INADIMPLENTE_MAT_INDEX1" ON "UFC_SEM"."CEI_INADIMPLENTE_MAT" ("CNPJ_CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."CEI_INADIMPLENTE_MAT"  IS 'snapshot table for snapshot UFC_SEM.CEI_INADIMPLENTE_MAT';
--------------------------------------------------------
--  DDL for Materialized View CEI_INADIMPLENCIA_MAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("CODIGO", "CODIGO_INFRACAO", "TIPO_INFRACAO", "VALOR_OBRIGACAO", "OBJETO_OBRIGACAO", "DATA_VENCIMENTO_OBRIGACAO", "DATA_INICIAL", "NUM_MESES", "OBSERVACAO", "DATA_EXCLUSAO", "DATA_INCLUSAO", "MOTIVO_EXCLUSAO", "UNIDADE_INCLUSAO", "USUARIO_INCLUSAO", "USUARIO_EXCLUSAO", "CNPJ_CPF_INADIMPLENTE")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT
     CODIGO,
          CODIGO_INFRACAO,
          TIPO_INFRACAO,
          VALOR_OBRIGACAO,
          OBJETO_OBRIGACAO,
          DATA_VENCIMENTO_OBRIGACAO,
          DATA_INICIAL,
          NUM_MESES,
          OBSERVACAO,
          DATA_EXCLUSAO,
          DATA_INCLUSAO,
          MOTIVO_EXCLUSAO,
          UNIDADE_INCLUSAO,
          USUARIO_INCLUSAO,
          USUARIO_EXCLUSAO,
          CNPJ_CPF_INADIMPLENTE
   FROM   CEI_INADIMPLENCIA_MAT@UFC.SEFAZ.MA.GOV.BR;

  CREATE UNIQUE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX1" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX10" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("DATA_EXCLUSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX11" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("DATA_INCLUSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX12" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("MOTIVO_EXCLUSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX13" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("UNIDADE_INCLUSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX14" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("USUARIO_INCLUSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX15" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("USUARIO_EXCLUSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX2" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("CODIGO_INFRACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX3" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("TIPO_INFRACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX4" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("VALOR_OBRIGACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX5" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("OBJETO_OBRIGACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX6" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("DATA_VENCIMENTO_OBRIGACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX7" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("DATA_INICIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX8" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("NUM_MESES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."CEI_INADIMPLENCIA_MAT_INDEX9" ON "UFC_SEM"."CEI_INADIMPLENCIA_MAT" ("OBSERVACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."CEI_INADIMPLENCIA_MAT"  IS 'snapshot table for snapshot UFC_SEM.CEI_INADIMPLENCIA_MAT';
