-- View de Entes Públicos (Compradores)
--
-- Objetivo: Estruturar e Fornecer dados dos Entes Públicos.
-- Campos retornados:
--  CNPJ: CNPJ DO ENTE PUBLICO (VARCHAR2(14))
--  NOME: NOME DO ENTE PUBLICO (VARCHAR2(200))
--  NATUREZA_JURIDICA: NATUREZA JURIDICA DO ENTE PUBLICO (VARCHAR2(120))
--  COD_NATUREZA: CODIGO NATUREZA DO ENTE PUBLICO (VARCHAR2(4))
--  CODIGO_SRF: CODIGO SRF (VARCHAR2(20))
--  MUNICIPIO: MUNICIPIO DO ENTE PUBLICO (VARCHAR2(50))
--  UF: UF DO ENTE PUBLICO (VARCHAR2(2))
--  ESFERA: ESFERA DO ENTE PUBLICO (VARCHAR2(100))
--  NIVEL: NIVEL (VARCHAR2(50))
--
-- PK: CNPJ
CREATE OR REPLACE VIEW "COMPRAS_ENTES_PUBLICOS" AS
  (
    SELECT ente.CNPJ, --CNPJ DO ENTE PUBLICO (VARCHAR2(14))
    ente.NOME,--NOME DO ENTE PUBLICO (VARCHAR2(200))
    ente.NATUREZA_JURIDICA,--NATUREZA JURIDICA DO ENTE PUBLICO (VARCHAR2(120))
    ente.COD_NATUREZA,--CODIGO NATUREZA DO ENTE PUBLICO (VARCHAR2(4))
    ente.CODIGO_SRF,--CODIGO SRF (VARCHAR2(20))
    ente.MUNICIPIO, --MUNICIPIO DO ENTE PUBLICO (VARCHAR2(50))
    ente.UF, --UF DO ENTE PUBLICO (VARCHAR2(2))
    ente.ESFERA,--ESFERA DO ENTE PUBLICO (VARCHAR2(100))
    ente.NIVEL--NIVEL (VARCHAR2(50))
    FROM 
    PUB_ENTES_PUBLICOS ente
) WITH READ ONLY;

   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."CNPJ" IS 'CNPJ DO ENTE PUBLICO (VARCHAR2(14))
';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."NOME" IS 'NOME DO ENTE PUBLICO (VARCHAR2(200))
';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."NATUREZA_JURIDICA" IS 'NATUREZA JURIDICA DO ENTE PUBLICO (VARCHAR2(120))

';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."COD_NATUREZA" IS 'CODIGO NATUREZA DO ENTE PUBLICO (VARCHAR2(4))


';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."CODIGO_SRF" IS 'CODIGO SRF (VARCHAR2(20))
';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."MUNICIPIO" IS 'MUNICIPIO DO ENTE PUBLICO (VARCHAR2(50))

';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."UF" IS 'UF DO ENTE PUBLICO (VARCHAR2(2))
';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."ESFERA" IS 'ESFERA DO ENTE PUBLICO (VARCHAR2(100))
';
   COMMENT ON COLUMN "COMPRAS_ENTES_PUBLICOS"."NIVEL" IS 'NIVEL (VARCHAR2(50))
';

-- View de Compra Pública
--
-- Objetivo: Estruturar e Fornecer dados das Compras Públicas.
-- Campos retornados:
--  ID_COMPRA_PUBLICA: ID DA NOTA FISCAL (NUMBER)
--  CPF_CNPJ_FORNECEDOR: CPF OU CNPJ DO FORNECEDOR (VARCHAR2(80))
--  CNPJ_ENTE_PUBLICO: CNPJ DO ENTE PÚBLICO (NUMBER(14)) 
--  NUMERO_PEDIDO: NUMERO DO PEDIDO (VARCHAR2(70))
--  CONTRATO: CONTRATO DA COMPRA (VARCHAR2(60))
--  NOTA_EMPENHO: NOTA EMPENHO (VARCHAR2(25))
-- 
-- PK: ID_COMPRA_PUBLICA
-- FK: CPF_CNPJ_FORNECEDOR, CNPJ_ENTE_PUBLICO

  CREATE MATERIALIZED VIEW "COMPRAS_COMPRA_PUBLICA" ("ID_COMPRA_PUBLICA", "CPF_CNPJ_FORNECEDOR", "CNPJ_ENTE_PUBLICO", "NUMERO_PEDIDO", "CONTRATO", "NOTA_EMPENHO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/24
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT compra.* 
FROM 
COMPRAS_COMPRA_PUBLICAS_MAT compra
INNER JOIN
COMPRAS_ENTES_PUBLICOS entes
ON
compra.CNPJ_ENTE_PUBLICO = entes.CNPJ;

  CREATE INDEX "COMPRAS_COMPRA_PUBLICA_INDEX1" ON "COMPRAS_COMPRA_PUBLICA" ("ID_COMPRA_PUBLICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
  CREATE INDEX "COMPRAS_COMPRA_PUBLICA_INDEX2" ON "COMPRAS_COMPRA_PUBLICA" ("CPF_CNPJ_FORNECEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
  CREATE INDEX "COMPRAS_COMPRA_PUBLICA_INDEX3" ON "COMPRAS_COMPRA_PUBLICA" ("CNPJ_ENTE_PUBLICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
  CREATE INDEX "COMPRAS_COMPRA_PUBLICA_INDEX4" ON "COMPRAS_COMPRA_PUBLICA" ("NUMERO_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

   COMMENT ON MATERIALIZED VIEW "COMPRAS_COMPRA_PUBLICA"  IS 'snapshot table for snapshot COMPRAS_COMPRA_PUBLICA';



    SELECT nota_fiscal.ID_INFNFE AS ID_COMPRA_PUBLICA,
    CONCAT(nota_fiscal.CNPJ,nota_fiscal.CPF) AS CPF_CNPJ_FORNECEDOR,
    destinatario.CNPJ AS CNPJ_ENTE_PUBLICO,
    compra.XPED AS NUMERO_PEDIDO,
    compra.XCONT AS CONTRATO,
    compra.XNEMP AS NOTA_EMPENHO
    FROM APL_NFE.EMIT@"ARMAHMLG.WORLD" nota_fiscal
    INNER JOIN
    APL_NFE.DEST@"ARMAHMLG.WORLD" destinatario
    ON
    nota_fiscal.ID_INFNFE = destinatario.ID_INFNFE
    INNER JOIN
    APL_NFE.COMPRA@"ARMAHMLG.WORLD"
    ON
    compra.ID_INFNFE = destinatario.ID_INFNFE
    AND
    destinatario.CNPJ IS NOT NULL
    INNER JOIN
    PUB_ENTES_PUBLICOS ente
    ON 
    destinatario.CNPJ = ente.CNPJ
-- View de Fornecedor
--
-- Objetivo: Estruturar e Fornecer dados dos Fornecedores de Compras Públicas.
-- Campos retornados:
--  CNPJ: CNPJ FORNECEDOR (NUMBER(14))
--  NOME: NOME FORNECEDOR (VARCHAR2(100))
--  NOME_FANTASIA: NOME FANTASIA FORNECEDOR (VARCHAR2(100))
--  INSCRICAO_ESTADUAL: INSCRIÇAO ESTADUAL DO FORNECEDOR (VARCHAR2(14))
--  INSCRICAO_MUNICIPAL: INSCRIÇAO MUNICIPAL DO FORNECEDOR (VARCHAR2(20))
--  CNAE: CNAE DO FORNECEDOR (NUMBER(7))
--  REGIME_TRIBUTARIO: REGIME TRIBUTARIO DO FORNECEDOR (NUMBER(1))
-- 
-- PK:CNPJ
CREATE OR REPLACE VIEW COMPRAS_FORNECEDOR AS
(
    SELECT * FROM COMPRAS_FORNECEDOR_MAT_
)
WITH READ ONLY;

-- View de Produto
--
-- Objetivo: Estruturar e Fornecer dados de Produto.
-- Campos retornados:
--  ID_PRODUTO: ID DO PRODUTO (NUMBER)
--  CODIGO_PRODUTO: CODIGO DO PRODUTO (VARCHAR2(65))
--  DESCRICAO: DESCRIÇAO DO PRODUTO (VARCHAR2(150))
--  CODIGO_EAN_BARRAS: CODIGO DE BARRAS (NUMBER(14))
-- 
-- PK: ID_PRODUTO
CREATE OR REPLACE VIEW COMPRAS_PRODUTO AS
(
    SELECT ID_PROD AS ID_PRODUTO,
        CPROD AS CODIGO_PRODUTO,
        XPROD AS DESCRICAO,
        CEAN AS CODIGO_EAN_BARRAS,
        QTRIB AS QUANTIDADE_TRIBUTAVEL,
        CFOP,
        CEST,
        VUNTRIB AS VALOR_UNITARIO_TRIBUTACAO,
        VPROD AS VALOR_UNITARIO,
        QTRIB AS QUANTIDADE_COMERCIAL,
        UCOM AS UNIDADE_COMERCIAL,
        NCM AS CODIGO_NCM,
        CEANTRIB AS CEAN_TRIB,
        ID_DET AS ID_DETALHAMENTO,
        XPED AS NUMERO_PEDIDO
    FROM APL_NFE.PROD@"DL_ARMA.SEFAZ.MA.GOV.BR" 
    INNER JOIN COMPRAS_COMPRA_PUBLICA
    ON
    ID_PROD = ID_COMPRA_PUBLICA
)
WITH READ ONLY;

-- View de Item
--
-- Objetivo: Estruturar e Fornecer dados de Itens envolvidos em Compras Públicas
-- Campos retornados:
--  ID_COMPRA: ID DA NOTA FISCAL (NUMBER)
--  ID_PRODUTO: ID DO PRODUTO (NUMBER)
--  NUMERO_ITEM: NUMERO DO ITEM (NUMBER(6))
-- 
--  PK: ID_COMPRA, ID_PRODUTO
--  FK: ID_COMPRA, ID_PRODUTO 
CREATE OR REPLACE VIEW COMPRAS_ITEM AS
(
    SELECT prod.ID_DETALHAMENTO AS ID_COMPRA,
        prod.ID_PRODUTO,
        DESCRICAO,
        det.NITEM AS NUMERO_ITEM,
        NUMERO_PEDIDO,
        det.INFADPROD AS INFORMACOES_ADICIONAIS
    FROM
        COMPRAS_PRODUTO prod
    INNER JOIN 
        APL_NFE.DET@DL_ARMA.SEFAZ.MA.GOV.BR det
    ON prod.ID_DETALHAMENTO = det.ID_DET
)
WITH READ ONLY;

--CREATE OR REPLACE VIEW COMPRAS_ITEM AS
--(
--    SELECT det.ID_INFNFE AS ID_COMPRA,
--        prod.ID_PROD AS ID_PRODUTO,
--        XPROD AS DESCRICAO,
--        det.NITEM AS NUMERO_ITEM,
--        prod.XPED AS NUMERO_PEDIDO,
--        det.INFADPROD AS INFORMACOES_ADICIONAIS
--    FROM
--        APL_NFE.PROD@"ARMAHMLG.WORLD" prod
--    INNER JOIN 
--        APL_NFE.DET@"ARMAHMLG.WORLD" det
--    ON prod.ID_DET = det.ID_DET
--    INNER JOIN
--    APL_NFE.COMPRA@"ARMAHMLG.WORLD" compra
--    ON 
--    det.ID_INFNFE = compra.ID_INFNFE
--)
--WITH READ ONLY;



-- View de Arma
--
-- Objetivo: Estruturar e Armazenar dados de Armas de Fogo
-- Campos retornados:
--  ID_ARMA : IDENTIFICADOR DA ARMA (NUMBER(38))
--  ID_PRODUTO: IDENTIFICADOR DE PRODUTO (NUMBER)
--  TIPO_ARMA: IDENTIFICA O TIPO DA ARMA (NUMBER)
--  NUMERO_SERIE: IDENTIFICA O NUMERO DE SERIE DA ARMA (VARCHAR2(15))
--  NUMERO_CANO: IDENTIFICA O NUMERO DO CANO DA ARMA (VARCHAR2(15))
--
-- PK: ID_ARMA
-- FK: ID_PRODUTO
CREATE OR REPLACE VIEW COMPRAS_ARMA AS
(
    SELECT  
        ID_ARMA AS ID_ARMA,
        ID_PROD AS ID_PRODUTO,
        TPARMA AS TIPO_ARMA,
        NSERIE AS NUMERO_SERIE,
        NCANO AS NUMERO_CANO,
        DESCR AS DESCRICAO_COMPLETA
    FROM APL_NFE.ARMA@DL_ARMA.SEFAZ.MA.GOV.BR
)
WITH READ ONLY;

-- View de Combustivel
--
-- Objetivo: Estruturar e Fornecer dados de Combustíveis.
-- Campos retornados:
--  ID_COMBUSTIVEL: IDENTIFICADOR DO COMBUSTÍVEL (NUMBER)
--  ID_PRODUTO: IDENTIFICADOR DE PRODUTO (NUMBER)
--  CODIGO_PRODUTO_ANP: CÓDIGO DO PRODUTO NA AGÊNCIA NACIONAL DO PETRÓLEO (NUMBER(10))
--  PERCENTUAL_GAS_NATURAL_GLP: PERCENTUAL DE GÁS NATURAL NO PETROLEO (NUMBER(13,2))
--  CODIGO_AUTORIZACAO: CÓDIGO DE AUTORIZAÇÃO DA COMPRA (NUMBER(30))
--  QUANTIDADE_COMBUSTIVEL_FATURADA: QUANTIDADE DE COMBUSTIVEL FATURADO (NUMBER(15,4))
--  UF_CONSUMO: UF EM QUESTAO (VARCHAR2(2))
--  DESCRICAO_ANP: DESCRIÇAO DO PRODUTO NA AGÊNCIA NACIONAL DO PETRÓLEO (VARCHAR2(100)) 
--  PERCENTUAL_GLP: PERCENTUAL DE GLP (NUMBER(10,4))
--  PERCENTUAL_GAS_NATURAL: PERCENTUAL DE GÁS NATURAL (NUMBER(10,4))
--  PERCENTUAL_GAS_IMPORTADO: PERCENTUAL DE GÁS IMPORTADO (NUMBER(10,4))
--  VALOR_PARTIDA: VALOR DA PARTIDA (NUMBER(13,2)3241E)
-- 
-- PK: ID_COMBUSTIVEL
-- FK: ID_PRODUTO (PRODUTO)



  CREATE MATERIALIZED VIEW "COMPRAS_COMBUSTIVEL" ("ID_COMBUSTIVEL", "ID_PRODUTO", "CODIGO_PRODUTO_ANP", "PERCENTUAL_GAS_NATURAL_GLP", "CODIGO_AUTORIZACAO", "QUANTIDADE_COMBUSTIVEL_FATURADA", "UF_CONSUMO", "DESCRICAO_ANP", "PERCENTUAL_GLP", "PERCENTUAL_GAS_NATURAL", "PERCENTUAL_GAS_IMPORTADO", "VALOR_PARTIDA", "DESCRICAO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1/24
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT 
        comb.ID_COMB AS ID_COMBUSTIVEL, -- IDENTIFICADOR DO COMBUSTÍVEL (NUMBER)
        comb.ID_PROD AS ID_PRODUTO, --IDENTIFICADOR DE PRODUTO (NUMBER)
        comb.CPRODANP AS CODIGO_PRODUTO_ANP, --CÓDIGO DO PRODUTO NA AGÊNCIA NACIONAL DO PETRÓLEO (NUMBER(10))
        comb.PMIXGN AS PERCENTUAL_GAS_NATURAL_GLP, --PERCENTUAL DE GÁS NATURAL NO PETROLEO (NUMBER(13,2))
        comb.CODIF AS CODIGO_AUTORIZACAO, --CODIGO_AUTORIZACAO: CÓDIGO DE AUTORIZAÇÃO DA COMPRA (NUMBER(30))
        comb.QTEMP AS QUANTIDADE_COMBUSTIVEL_FATURADA, -- QUANTIDADE_COMBUSTIVEL_FATURADA: QUANTIDADE DE COMBUSTIVEL FATURADO (NUMBER(15,4))
        comb.UFCONS AS UF_CONSUMO, --UF_CONSUMO: UF EM QUESTAO (VARCHAR2(2))
        comb.DESCANP AS DESCRICAO_ANP, -- DESCRIÇAO DO PRODUTO NA AGÊNCIA NACIONAL DO PETRÓLEO (VARCHAR2(100))
        comb.PGLP AS PERCENTUAL_GLP, -- PERCENTUAL_GLP: PERCENTUAL DE GLP (NUMBER(10,4))
        comb.PGNN AS PERCENTUAL_GAS_NATURAL, -- PERCENTUAL_GAS_NATURAL: PERCENTUAL DE GÁS NATURAL (NUMBER(10,4))
        comb.PGNI AS PERCENTUAL_GAS_IMPORTADO, -- PERCENTUAL_GAS_IMPORTADO: PERCENTUAL DE GÁS IMPORTADO (NUMBER(10,4))
        comb.VPART AS VALOR_PARTIDA, -- VALOR_PARTIDA: VALOR DA PARTIDA (NUMBER(13,2)3241E)
        prod.XPROD AS DESCRICAO
        FROM APL_NFE.COMB@"ARMAHMLG.WORLD" comb
    INNER JOIN APL_NFE.prod@"ARMAHMLG.WORLD" prod
    ON comb.ID_PROD = prod.ID_PROD;

  CREATE INDEX "COMPRAS_COMBUSTIVEL_INDEX1" ON "COMPRAS_COMBUSTIVEL" ("ID_COMBUSTIVEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  CREATE INDEX "COMPRAS_COMBUSTIVEL_INDEX2" ON "COMPRAS_COMBUSTIVEL" ("ID_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  CREATE INDEX "COMPRAS_COMBUSTIVEL_INDEX3" ON "COMPRAS_COMBUSTIVEL" ("CODIGO_PRODUTO_ANP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;

   COMMENT ON MATERIALIZED VIEW "COMPRAS_COMBUSTIVEL"  IS 'snapshot table for snapshot UFC2.COMPRAS_COMBUSTIVEL';


--CREATE OR REPLACE VIEW COMPRAS_COMBUSTIVEL AS
--(
--    SELECT 
--        ID_COMB AS ID_COMBUSTIVEL,
--        ID_PROD AS ID_PRODUTO,
--        CPRODANP AS CODIGO_PRODUTO_ANP,
--        PMIXGN AS PERCENTUAL_GAS_NATURAL_GLP,
--        CODIF AS CODIGO_AUTORIZACAO,
--        QTEMP AS QUANTIDADE_COMBUSTIVEL_FATURADA,
--        UFCONS AS UF_CONSUMO,
--        DESCANP AS DESCRICAO_ANP,
--        PGLP AS PERCENTUAL_GLP,
--        PGNN AS PERCENTUAL_GAS_NATURAL,
--        PGNI AS PERCENTUAL_GAS_IMPORTADO,
--        VPART AS VALOR_PARTIDA
--    FROM APL_NFE.COMB@DL_ARMA.SEFAZ.MA.GOV.BR
--)
--WITH READ ONLY;

-- View de Medicamento
--
-- Objetivo: Estruturar e Fornecer dados de Medicamentos.
--  ID_MEDICAMENTO: ID DO MEDICAMENTO (NUMBER)
--  ID_PRODUTO: ID DO PRODUTO (NUMBER)
--  NUMERO_LOTE: NUMERO DO LOTE (VARCHAR2(20))
--  QUANTIDADE: QUANTIDADE DE MEDICAMENTO (NUMBER(13,3))
--  DATA_FABRICACAO: DATA DE FABRICAÇAO DO MEDICAMENTO (DATE)
--  DATA_VALIDADE: DATA DE VALIDADE DO MEDICAMENTO (DATE)
--  PRECO_MAXIMO_CONSUMIDOR: PREÇO MAXIMO (NUMBER(13,2))
--  CODIGO_PRODUTO_ANVISA: CODIGO DO PRODUTO NA ANVISA (VARCHAR2(15))
--  MOTIVO_ISENCAO_ANVISA: MOTIVO ISENCAO NA ANVISA (VARCHAR2(255))
--
-- PK: ID_MEDICAMENTO
-- FK: ID_PRODUTO 
CREATE OR REPLACE VIEW COMPRAS_MEDICAMENTO AS
(
    SELECT DISTINCT 
        ID_MED AS ID_MEDICAMENTO, --ID DO MEDICAMENTO (NUMBER)
        prod.ID_PROD AS ID_PRODUTO,--ID DO PRODUTO (NUMBER)
        NLOTE AS NUMERO_LOTE,--NUMERO DO LOTE (VARCHAR2(20))
        QLOTE AS QUANTIDADE,--QUANTIDADE DE MEDICAMENTO (NUMBER(13,3))
        DFAB AS DATA_FABRICACAO,--DATA DE FABRICAÇAO DO MEDICAMENTO (DATE)
        DVAL AS DATA_VALIDADE,--DATA DE VALIDADE DO MEDICAMENTO (DATE)
        VPMC AS PRECO_MAXIMO_CONSUMIDOR,--PREÇO MAXIMO (NUMBER(13,2))
        CPRODANVISA AS CODIGO_PRODUTO_ANVISA,--CODIGO DO PRODUTO NA ANVISA (VARCHAR2(15))
        XMOTIVOISENCAO AS MOTIVO_ISENCAO_ANVISA,--MOTIVO ISENCAO NA ANVISA (VARCHAR2(255))
        XPROD AS DESCRICAO
    FROM APL_NFE.MED@DL_ARMA med
    INNER JOIN APL_NFE.prod@DL_ARMA prod
    ON med.ID_PROD = prod.ID_PROD
)
WITH READ ONLY;