--criacao das tabelas normalizadas da RFB no oracle
CREATE TABLE RFB_ATIVIDADE_ECONOMICA 
(
  URI VARCHAR2(7 CHAR) 
, CNAE VARCHAR2(7 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_BAIRRO 
(
  URI VARCHAR2(4000 BYTE) 
, ROTULO VARCHAR2(50 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_CIDADE 
(
  URI VARCHAR2(4000 BYTE) 
, ROTULO VARCHAR2(50 CHAR) 
, CODIGO_MUNICIPIO VARCHAR2(4 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_CIDADE_ESTRANGEIRA 
(
  URI VARCHAR2(4000 BYTE) 
, ROTULO VARCHAR2(55 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_EMPRESA 
(
  URI VARCHAR2(4000 CHAR) 
, CNPJ_RAIZ VARCHAR2(9 CHAR) 
, RAZAO_SOCIAL VARCHAR2(150 CHAR) 
, CAPITAL_SOCIAL NUMBER --ADD COLUNA DA TB ESTABELECIMENTO
, ENTE_FEDERATIVO VARCHAR2(156 BYTE) --ADD COLUNA
, URI_OPCAO_SIMPLES VARCHAR2(21 CHAR) 
--, E_MEI VARCHAR2(5 BYTE) REMOVE COLUNA
, URI_PORTE VARCHAR2(13 BYTE) --ADD COLUNA DA TB ESTABELECIMENTO
, URI_MEI VARCHAR2() --ADD COLUNA PARA NOVA TABELA RFB_OPCAO_MEI
, URI_QUALIFICACAO_REPRESENTANTE VARCHAR2(512 BYTE) 
, URI_NATUREZA_LEGAL VARCHAR2(512 BYTE) 
, URI_ESTABELECIMENTO_MATRIZ VARCHAR2(4000 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_empresa 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_EMPRESA_HOLDING 
(
  URI VARCHAR2(4000 BYTE) 
, RAZAO_SOCIAL VARCHAR2(150 CHAR) 
, CNPJ_RAIZ VARCHAR2(9 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE ENDERECO 
(
  URI RAW(2000) 
, NUMERO VARCHAR2(6 CHAR) 
, COMPLEMENTO VARCHAR2(156 CHAR) 
, CEP VARCHAR2(8 CHAR) 
, URI_UNIDADE_FEDERATIVA VARCHAR2(19 BYTE) 
, URI_PAIS VARCHAR2(4000 BYTE) 
, URI_MUNICIPIO VARCHAR2(4000 BYTE) 
, URI_CIDADE_EXTERIOR VARCHAR2(4000 BYTE) 
, URI_BAIRRO VARCHAR2(4000 BYTE) 
, URI_LOGRADOURO VARCHAR2(4000 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_ESTABELECIMENTO 
(
  URI VARCHAR2(4000 BYTE) 
, CNPJ VARCHAR2(14 CHAR) 
, RAZAO_SOCIAL VARCHAR2(150 CHAR) 
, NOME_FANTASIA VARCHAR2(56 CHAR) 
--, URI_PORTE VARCHAR2(13 BYTE) REMOVE COLUNA PARA TB EMPRESA
, EMAIL VARCHAR2(115 CHAR) 
--, CAPITAL_SOCIAL NUMBER REMOVE COLUNA PARA TB EMPRESA
, URI_E_MATRIZ_OU_FILIAL CHAR(6 BYTE) 
, URI_PRINCIPAL_ATIV_ECONOMICA VARCHAR2(7 CHAR) 
, DATA_INICIO_ATIV DATE 
, URI_ENDERECO RAW(2000) 
, TELEFONE1 VARCHAR2(15 CHAR) 
, TELEFONE2 VARCHAR2(15 CHAR) 
, FAX VARCHAR2(15 CHAR) 
, URI_SITUACAO VARCHAR2(76 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_estabelecimento 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE ESTRANGEIRO 
(
  URI VARCHAR2(4000 BYTE) 
, NOME VARCHAR2(150 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE LOGRADOURO 
(
  URI VARCHAR2(4000 BYTE) 
, ROTULO VARCHAR2(60 CHAR) 
, TIPO_LOGRADOURO VARCHAR2(21 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE NATUREZA_LEGAL 
(
  URI VARCHAR2(512 BYTE) 
, ROTULO VARCHAR2(128 BYTE) 
, CODIGO VARCHAR2(26 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE OPCAO_SIMPLES 
(
  URI VARCHAR2(21 CHAR) 
, TIPO_SIMPLES CHAR(1 BYTE) 
, SUB_CLASSE_SIMPLES VARCHAR2(10 BYTE) 
, DATA_EXCLUSAO_SIMPLES DATE 
, DATA_OPCAO_SIMPLES DATE 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE PAIS 
(
  URI VARCHAR2(4000 BYTE) 
, ROTULO VARCHAR2(280 BYTE) 
, CODIGO_PAIS NUMBER(*, 0) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_PESSOA 
(
  URI VARCHAR2(4000 BYTE) 
, CPF VARCHAR2(14 CHAR) 
, NOME VARCHAR2(150 CHAR) 
, FAIXA_ETARIA VARCHAR2(1 BYTE) --ADD NOVA COLUNA
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE QUALIFICACAO 
(
  URI VARCHAR2(512 BYTE) 
, CODIGO_QUALIFICACAO NUMBER(*, 0) 
, ROTULO VARCHAR2(128 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RAZAO_SITUACAO_CADASTRAL 
(
  URI VARCHAR2(512 BYTE) 
, ROTULO VARCHAR2(128 BYTE) 
, CODIGO_RAZAO_SITUACAO NUMBER(*, 0) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE SITUACAO_CADASTRAL 
(
  URI VARCHAR2(76 BYTE) 
, DATA_SITUACAO_CADASTRAL DATE 
, URI_CLASSE_TIPO_SITUACAO VARCHAR2(9 BYTE) 
, URI_MOTIVO_SITUACAO VARCHAR2(512 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE SITUACAO_ESPECIAL 
(
  URI VARCHAR2(47 BYTE) 
, DATA_INICIO_SIT_ESPECIAL DATE 
, DESCRICAO VARCHAR2(23 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE SOCIEDADE_COM_ESTRANGEIRO 
(
  URI VARCHAR2(4000 CHAR) 
, DATA_INICIO_SOCIEDADE DATE 
, ROTULO VARCHAR2(730 BYTE) 
, URI_QUALIFICACAO_REPRESENTANTE VARCHAR2(512 BYTE) 
, URI_SOCIO VARCHAR2(4000 BYTE) 
, URI_REPRESENTANTE VARCHAR2(4000 CHAR) 
, URI_QUALIFICACAO_SOCIO VARCHAR2(512 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE SOCIEDADE_COM_HOLDING 
(
  URI VARCHAR2(4000 CHAR) 
, ROTULO VARCHAR2(730 BYTE) 
, DATA_INICIO_SOCIEDADE DATE 
, URI_QUALIFICACAO_REPRESENTANTE VARCHAR2(512 BYTE) 
, URI_SOCIO VARCHAR2(4000 CHAR) 
, URI_REPRESENTANTE VARCHAR2(4000 CHAR) 
, URI_QUALIFICACAO_SOCIO VARCHAR2(512 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE SOCIEDADE_COM_PESSOA_FISICA 
(
  URI VARCHAR2(4000 CHAR) 
, DATA_INICIO_SOCIEDADE DATE 
, ROTULO VARCHAR2(730 BYTE) 
, URI_SOCIO VARCHAR2(4000 CHAR) 
, URI_QUALIFICACAO_SOCIO VARCHAR2(512 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE UNIDADE_FEDERATIVA 
(
  URI VARCHAR2(19 BYTE) 
, ROTULO VARCHAR2(19 BYTE) 
, ABREVIACAO_UF VARCHAR2(2 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE TEM_ATIV_ECONOMICA_SECUNDARIA 
(
  URI_ESTABELECIMENTO VARCHAR2(4000 BYTE) 
, URI_ATIVIDADE_ECONOMICA VARCHAR2(7 CHAR) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE TEM_ESTABELECIMENTO 
(
  URI_EMPRESA VARCHAR2(4000 BYTE) 
, URI_ESTABELECIMENTO VARCHAR2(4000 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE TEM_SITUACAO_ESPECIAL 
(
  URI_EMPRESA VARCHAR2(4000 BYTE) 
, URI_SITUACAO_ESPECIAL VARCHAR2(47 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE TEM_SOCIEDADE_ESTRANGEIRA 
(
  URI_EMPRESA VARCHAR2(4000 BYTE) 
, URI_SOCIEDADE VARCHAR2(4000 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE TEM_SOCIEDADE_FISICA 
(
  URI_EMPRESA VARCHAR2(4000 BYTE) 
, URI_SOCIEDADE VARCHAR2(4000 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE TEM_SOCIEDADE_JURIDICA 
(
  URI_EMPRESA VARCHAR2(4000 BYTE) 
, URI_SOCIEDADE VARCHAR2(4000 BYTE) 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE TABLE RFB_OPCAO_MEI 
(
  URI VARCHAR2(21 CHAR) 
, OPC_MEI CHAR(1 BYTE) 
, DATA_OPC_MEI DATE 
, DATA_EXC_MEI DATE 
) 
LOGGING 
TABLESPACE ts_norm_demais_tb 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;