--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Marà¸£à¸‡o-02-2022   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table RFB_ESTABELECIMENTO
--------------------------------------------------------

  CREATE TABLE "RFB_ESTABELECIMENTO" 
   (	"CNPJ" VARCHAR2(14 BYTE), 
	"RAZAO_SOCIAL" VARCHAR2(150 CHAR), 
	"NOME_FANTASIA" VARCHAR2(70 BYTE), 
	"EMAIL" VARCHAR2(115 BYTE), 
	"TIPO_ESTABELECIMENTO" CHAR(6 BYTE), 
	"URI_ATIVIDADE_ECONOMICA" VARCHAR2(7 BYTE), 
	"DATA_INICIO_ATIV" VARCHAR2(8 BYTE), 
	"URI_ENDERECO_NACIONAL" VARCHAR2(100 BYTE), 
	"TELEFONE_1" VARCHAR2(15 BYTE), 
	"TELEFONE_2" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"URI_SITUACAO" VARCHAR2(200 BYTE), 
	"URI" VARCHAR2(100 BYTE), 
	"ID_ATIVIDADE_ECONOMICA" VARCHAR2(20 BYTE), 
	"ID_ENDERECO" VARCHAR2(50 BYTE), 
	"ID_SITUACAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;
--------------------------------------------------------
--  DDL for Table RFB_ENDERECO_EXTERIOR
--------------------------------------------------------

  CREATE TABLE "RFB_ENDERECO_EXTERIOR" 
   (	"URI" VARCHAR2(100 BYTE), 
	"CEP" VARCHAR2(8 CHAR), 
	"PAIS" VARCHAR2(4000 BYTE), 
	"CIDADE_EXTERIOR" VARCHAR2(4000 BYTE), 
	"ID_ENDERECO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_ENDERECO
--------------------------------------------------------

  CREATE TABLE "RFB_ENDERECO" 
   (	"URI" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(19 BYTE), 
	"CIDADE" VARCHAR2(200 BYTE), 
	"LOGRADOURO" VARCHAR2(200 BYTE), 
	"NUMERO" VARCHAR2(20 CHAR), 
	"COMPLEMENTO" VARCHAR2(156 CHAR), 
	"CEP" VARCHAR2(8 CHAR), 
	"BAIRRO" VARCHAR2(100 BYTE), 
	"PAIS" VARCHAR2(100 BYTE), 
	"ID_ENDERECO" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_EMPRESA_HOLDING
--------------------------------------------------------

  CREATE TABLE "RFB_EMPRESA_HOLDING" 
   (	"URI" VARCHAR2(4000 BYTE), 
	"RAZAO_SOCIAL" VARCHAR2(150 CHAR), 
	"CNPJ_RAIZ" VARCHAR2(9 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_EMPRESA
--------------------------------------------------------

  CREATE TABLE "RFB_EMPRESA" 
   (	"URI" VARCHAR2(4000 CHAR), 
	"CNPJ_RAIZ" VARCHAR2(9 CHAR), 
	"RAZAO_SOCIAL" VARCHAR2(150 CHAR), 
	"URI_OPCAO_SIMPLES" VARCHAR2(69 CHAR), 
	"URI_OPCAO_MEI" VARCHAR2(65 CHAR), 
	"CAPITAL_SOCIAL" NUMBER, 
	"TEM_PORTE" VARCHAR2(24 BYTE), 
	"ENTE_FEDERATIVO" VARCHAR2(156 BYTE), 
	"URI_QUALIFICACAO_REPRESENTANTE" VARCHAR2(512 BYTE), 
	"URI_NATUREZA_LEGAL" VARCHAR2(512 BYTE), 
	"URI_ESTABELECIMENTO_MATRIZ" VARCHAR2(300 CHAR), 
	"ID_OPCAO_SIMPLES" VARCHAR2(21 BYTE), 
	"ID_OPCAO_MEI" VARCHAR2(21 BYTE), 
	"ID_QUALIFICACAO_REPRESENTANTE" VARCHAR2(459 BYTE), 
	"ID_NATUREZA_LEGAL" VARCHAR2(512 BYTE), 
	"ID_ESTABELECIMENTO_MATRIZ" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_EMPRESA"   NO INMEMORY ;



--------------------------------------------------------
--  DDL for Table RFB_TEM_SOCIEDADE_JURIDICA
--------------------------------------------------------

  CREATE TABLE "RFB_TEM_SOCIEDADE_JURIDICA" 
   (	"URI_EMPRESA" VARCHAR2(4000 BYTE), 
	"URI_SOCIEDADE" VARCHAR2(4000 BYTE), 
	"ID_EMPRESA" VARCHAR2(20 BYTE), 
	"ID_SOCIEDADE" VARCHAR2(220 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_TEM_SOCIEDADE_FISICA
--------------------------------------------------------

  CREATE TABLE "RFB_TEM_SOCIEDADE_FISICA" 
   (	"URI_EMPRESA" VARCHAR2(4000 BYTE), 
	"URI_SOCIEDADE" VARCHAR2(4000 BYTE), 
	"ID_EMPRESA" VARCHAR2(20 BYTE), 
	"ID_SOCIEDADE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_TEM_SOCIEDADE_ESTRANGEIRA
--------------------------------------------------------

  CREATE TABLE "RFB_TEM_SOCIEDADE_ESTRANGEIRA" 
   (	"URI_EMPRESA" VARCHAR2(4000 BYTE), 
	"URI_SOCIEDADE" VARCHAR2(4000 BYTE), 
	"ID_EMPRESA" VARCHAR2(20 BYTE), 
	"ID_SOCIEDADE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_TEM_SITUACAO_ESPECIAL
--------------------------------------------------------

  CREATE TABLE "RFB_TEM_SITUACAO_ESPECIAL" 
   (	"URI_EMPRESA" VARCHAR2(4000 BYTE), 
	"URI_SITUACAO_ESPECIAL" VARCHAR2(100 BYTE), 
	"ID_EMPRESA" VARCHAR2(20 BYTE), 
	"ID_SITUACAO_ESPECIAL" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_TEM_ESTABELECIMENTO
--------------------------------------------------------

  CREATE TABLE "RFB_TEM_ESTABELECIMENTO" 
   (	"URI_EMPRESA" VARCHAR2(4000 BYTE), 
	"URI_ESTABELECIMENTO" VARCHAR2(4000 BYTE), 
	"ID_EMPRESA" VARCHAR2(20 BYTE), 
	"ID_ESTABELECIMENTO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_TEM_ATIV_ECONOMICA_SECUNDARIA
--------------------------------------------------------

  CREATE TABLE "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA" 
   (	"URI_ESTABELECIMENTO" VARCHAR2(73 BYTE), 
	"URI_ATIVIDADE_ECONOMICA" VARCHAR2(67 CHAR), 
	"ID_ESTABELECIMENTO" VARCHAR2(17 BYTE), 
	"ID_ATIVIDADE_ECONOMICA" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_SOCIEDADE_COM_PESSOA_FISICA
--------------------------------------------------------

  CREATE TABLE "RFB_SOCIEDADE_COM_PESSOA_FISICA" 
   (	"URI" VARCHAR2(4000 CHAR), 
	"ROTULO" VARCHAR2(730 BYTE), 
	"DATA_INICIO_SOCIEDADE" DATE, 
	"URI_SOCIO" VARCHAR2(4000 CHAR), 
	"URI_QUALIFICACAO_SOCIO" VARCHAR2(512 BYTE), 
	"URI_REPRESENTANTE" VARCHAR2(4000 CHAR), 
	"URI_QUALIFICACAO_REPRESENTANTE" VARCHAR2(512 BYTE), 
	"ID_SOCIEDADE" VARCHAR2(230 BYTE), 
	"ID_QUALIFICACAO_SOCIO" VARCHAR2(230 BYTE), 
	"ID_QUALIFICACAO_REPRESENTANTE" VARCHAR2(230 BYTE), 
	"ID_REPRESENTANTE" VARCHAR2(230 BYTE), 
	"ID_SOCIO" VARCHAR2(230 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_SOCIEDADE_COM_HOLDING
--------------------------------------------------------

  CREATE TABLE "RFB_SOCIEDADE_COM_HOLDING" 
   (	"URI" VARCHAR2(4000 CHAR), 
	"ROTULO" VARCHAR2(730 BYTE), 
	"DATA_INICIO_SOCIEDADE" DATE, 
	"URI_QUALIFICACAO_REPRESENTANTE" VARCHAR2(512 BYTE), 
	"URI_SOCIO" VARCHAR2(4000 CHAR), 
	"URI_REPRESENTANTE" VARCHAR2(4000 CHAR), 
	"URI_QUALIFICACAO_SOCIO" VARCHAR2(512 BYTE), 
	"ID_SOCIEDADE" VARCHAR2(300 BYTE), 
	"ID_QUALIFICACAO_REPRESENTANTE" VARCHAR2(200 BYTE), 
	"ID_QUALIFICACAO_SOCIO" VARCHAR2(200 BYTE), 
	"ID_SOCIO" VARCHAR2(200 BYTE), 
	"ID_REPRESENTANTE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_SOCIEDADE_COM_ESTRANGEIRO
--------------------------------------------------------

  CREATE TABLE "RFB_SOCIEDADE_COM_ESTRANGEIRO" 
   (	"URI" VARCHAR2(4000 CHAR), 
	"DATA_INICIO_SOCIEDADE" DATE, 
	"ROTULO" VARCHAR2(730 BYTE), 
	"URI_QUALIFICACAO_REPRESENTANTE" VARCHAR2(512 BYTE), 
	"URI_SOCIO" VARCHAR2(4000 BYTE), 
	"URI_REPRESENTANTE" VARCHAR2(4000 CHAR), 
	"URI_QUALIFICACAO_SOCIO" VARCHAR2(512 BYTE), 
	"ID_QUALIFICACAO_REPRESENTANTE" VARCHAR2(180 BYTE), 
	"ID_SOCIO" VARCHAR2(80 BYTE), 
	"ID_QUALIFICACAO_SOCIO" VARCHAR2(180 BYTE), 
	"ID_REPRESENTANTE" VARCHAR2(100 BYTE), 
	"ID_SOCIEDADE" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_SITUACAO_ESPECIAL
--------------------------------------------------------

  CREATE TABLE "RFB_SITUACAO_ESPECIAL" 
   (	"URI" VARCHAR2(100 BYTE), 
	"DATA_INICIO_SIT_ESPECIAL" DATE, 
	"DESCRICAO" VARCHAR2(25 CHAR), 
	"ID_SITUACAO_ESPECIAL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_SITUACAO_CADASTRAL
--------------------------------------------------------

  CREATE TABLE "RFB_SITUACAO_CADASTRAL" 
   (	"URI" VARCHAR2(100 BYTE), 
	"DATA_SITUACAO_CADASTRAL" DATE, 
	"TIPO_SITUACAO" VARCHAR2(9 BYTE), 
	"ID_RAZAO_SITUACAO" VARCHAR2(512 BYTE), 
	"ID_SITUACAO_CADASTRAL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_QUALIFICACAO
--------------------------------------------------------

  CREATE TABLE "RFB_QUALIFICACAO" 
   (	"URI" VARCHAR2(512 BYTE), 
	"CODIGO_QUALIFICACAO" NUMBER(*,0), 
	"ROTULO" VARCHAR2(128 BYTE), 
	"ID_QUALIFICACAO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_RAZAO_SITUACAO_CADASTRAL
--------------------------------------------------------

  CREATE TABLE "RFB_RAZAO_SITUACAO_CADASTRAL" 
   (	"URI" VARCHAR2(512 BYTE), 
	"ROTULO" VARCHAR2(128 BYTE), 
	"CODIGO_RAZAO_SITUACAO" NUMBER(*,0), 
	"ID_RAZAO_SITUACAO_CADASTRAL" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_PESSOA
--------------------------------------------------------

  CREATE TABLE "RFB_PESSOA" 
   (	"URI" VARCHAR2(4000 BYTE), 
	"CPF" VARCHAR2(14 CHAR), 
	"NOME" VARCHAR2(150 CHAR), 
	"FAIXA_ETARIA" VARCHAR2(1 BYTE), 
	"ID_PESSOA" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_OPCAO_SIMPLES
--------------------------------------------------------

  CREATE TABLE "RFB_OPCAO_SIMPLES" 
   (	"URI" VARCHAR2(80 CHAR), 
	"TIPO_SIMPLES" CHAR(1 BYTE), 
	"SUB_CLASSE_SIMPLES" VARCHAR2(10 BYTE), 
	"DATA_EXCLUSAO_SIMPLES" VARCHAR2(10 BYTE), 
	"DATA_OPCAO_SIMPLES" VARCHAR2(10 BYTE), 
	"ID_OPCAO_SIMPLES" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_OPCAO_MEI
--------------------------------------------------------

  CREATE TABLE "RFB_OPCAO_MEI" 
   (	"URI" VARCHAR2(80 CHAR), 
	"TIPO_MEI" CHAR(1 BYTE), 
	"DATA_EXCLUSAO_SIMPLES" VARCHAR2(10 BYTE), 
	"DATA_OPCAO_SIMPLES" VARCHAR2(10 BYTE), 
	"ID_OPCAO_MEI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_NATUREZA_LEGAL
--------------------------------------------------------

  CREATE TABLE "RFB_NATUREZA_LEGAL" 
   (	"URI" VARCHAR2(512 BYTE), 
	"CODIGO" VARCHAR2(26 BYTE), 
	"ROTULO" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_FAIXA_ETARIA
--------------------------------------------------------

  CREATE TABLE "RFB_FAIXA_ETARIA" 
   (	"URI_FAIXA_ETARIA" VARCHAR2(1 BYTE), 
	"CODIGO" VARCHAR2(1 BYTE), 
	"DESCRICAO" VARCHAR2(18 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;
--------------------------------------------------------
--  DDL for Table RFB_ESTRANGEIRO
--------------------------------------------------------

  CREATE TABLE "RFB_ESTRANGEIRO" 
   (	"URI" VARCHAR2(150 BYTE), 
	"NOME" VARCHAR2(150 CHAR), 
	"ID_PAIS" VARCHAR2(50 BYTE), 
	"ID_ESTRANGEIRO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_DEMAIS_TB" ;


--------------------------------------------------------
--  DDL for Table RFB_ESTABELECIMENTO_EXTERIOR
--------------------------------------------------------
 CREATE TABLE "RFB_ESTABELECIMENTO_EXTERIOR" 
   (	"URI" VARCHAR2(80 BYTE), 
	"CNPJ" VARCHAR2(14 BYTE), 
	"RAZAO_SOCIAL" VARCHAR2(170 BYTE), 
	"NOME_FANTASIA" VARCHAR2(70 BYTE), 
	"EMAIL" VARCHAR2(115 BYTE), 
	"TIPO_ESTABELECIMENTO" CHAR(6 BYTE), 
	"URI_ATIVIDADE_ECONOMICA" VARCHAR2(80 BYTE), 
	"DATA_INICIO_ATIV" VARCHAR2(8 BYTE), 
	"URI_ENDERECO_EXTERIOR" VARCHAR2(100 BYTE), 
	"TELEFONE_1" VARCHAR2(15 BYTE), 
	"TELEFONE_2" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"URI_SITUACAO" VARCHAR2(120 BYTE), 
	"ID_ATIVIDADE_ECONOMICA" VARCHAR2(20 BYTE), 
	"ID_ENDERECO" VARCHAR2(50 BYTE), 
	"ID_SITUACAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_NORM_ESTABELECIMENTO" ;


