--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SOCIEDADE_EMPRESA_JUR
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SOCIEDADE_EMPRESA_JUR" ON "RFB_TEM_SOCIEDADE_JURIDICA" ("URI_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SOCIEDADE_SOCIEDADE_JUR
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SOCIEDADE_SOCIEDADE_JUR" ON "RFB_TEM_SOCIEDADE_JURIDICA" ("URI_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SOCIEDADE_EMPRESA_FIS
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SOCIEDADE_EMPRESA_FIS" ON "RFB_TEM_SOCIEDADE_FISICA" ("URI_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SOCIEDADE_SOCIEDADE_FIS
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SOCIEDADE_SOCIEDADE_FIS" ON "RFB_TEM_SOCIEDADE_FISICA" ("URI_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SOCIEDADE_EMPRESA
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SOCIEDADE_EMPRESA" ON "RFB_TEM_SOCIEDADE_ESTRANGEIRA" ("URI_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SOCIEDADE_SOCIEDADE
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SOCIEDADE_SOCIEDADE" ON "RFB_TEM_SOCIEDADE_ESTRANGEIRA" ("URI_SOCIEDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SITU_EMPRESA
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SITU_EMPRESA" ON "RFB_TEM_SITUACAO_ESPECIAL" ("URI_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_SITU_ESPECIAL_ESP
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_SITU_ESPECIAL_ESP" ON "RFB_TEM_SITUACAO_ESPECIAL" ("URI_SITUACAO_ESPECIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_ESTAB_EMPRESA
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_ESTAB_EMPRESA" ON "RFB_TEM_ESTABELECIMENTO" ("URI_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_TEM_ESTAB_ESTABELECIMETO
--------------------------------------------------------

  CREATE INDEX "PK_RFB_TEM_ESTAB_ESTABELECIMETO" ON "RFB_TEM_ESTABELECIMENTO" ("URI_ESTABELECIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_ATIV_ESTAB
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_ATIV_ESTAB" ON "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA" ("URI_ESTABELECIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index RFB_TEM_ATIV_ECONOM
--------------------------------------------------------

  CREATE INDEX "RFB_TEM_ATIV_ECONOM" ON "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA" ("URI_ATIVIDADE_ECONOMICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_SOCIEDADE_COM_PESSOA_FISICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_SOCIEDADE_COM_PESSOA_FISICA" ON "RFB_SOCIEDADE_COM_PESSOA_FISICA" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_SOCIEDADE_COM_HOLDING
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_SOCIEDADE_COM_HOLDING" ON "RFB_SOCIEDADE_COM_HOLDING" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_SOCIEDADE_COM_ESTRANGEIRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_SOCIEDADE_COM_ESTRANGEIRO" ON "RFB_SOCIEDADE_COM_ESTRANGEIRO" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_SITUACAO_ESPECIAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_SITUACAO_ESPECIAL" ON "RFB_SITUACAO_ESPECIAL" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_SITUACAO_CADASTRAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_SITUACAO_CADASTRAL" ON "RFB_SITUACAO_CADASTRAL" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_QUALIFICACAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_QUALIFICACAO" ON "RFB_QUALIFICACAO" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_RAZAO_SITUACAO_CADASTRAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_RAZAO_SITUACAO_CADASTRAL" ON "RFB_RAZAO_SITUACAO_CADASTRAL" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_PESSOA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PESSOA" ON "RFB_PESSOA" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_OPCAO_SIMPLES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_OPCAO_SIMPLES" ON "RFB_OPCAO_SIMPLES" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_OPCAO_MEI
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_OPCAO_MEI" ON "RFB_OPCAO_MEI" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_NATUREZA_LEGAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_NATUREZA_LEGAL" ON "RFB_NATUREZA_LEGAL" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_FAIXA_ETARIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_FAIXA_ETARIA" ON "RFB_FAIXA_ETARIA" ("URI_FAIXA_ETARIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_ESTRANGEIRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_ESTRANGEIRO" ON "RFB_ESTRANGEIRO" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_RFB_ENDERECO_EXTERIOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_ENDERECO_EXTERIOR" ON "RFB_ENDERECO_EXTERIOR" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_EMPRESA_HOLDING
--------------------------------------------------------

  CREATE INDEX "PK_EMPRESA_HOLDING" ON "RFB_EMPRESA_HOLDING" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index RFB_EMPRESA_HOLDING_INDEX1
--------------------------------------------------------

  CREATE INDEX "RFB_EMPRESA_HOLDING_INDEX1" ON "RFB_EMPRESA_HOLDING" ("CNPJ_RAIZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  
--------------------------------------------------------
--  DDL for Index PK_RFB_ESTABELECIMENTO_EXTERIOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_RFB_ESTABELECIMENTO_EXTERIOR" ON "RFB_ESTABELECIMENTO_EXTERIOR" ("URI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;

--------------------------------------------------------
--  Constraints for Table RFB_TEM_SOCIEDADE_JURIDICA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SOCIEDADE_JURIDICA" MODIFY ("URI_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "RFB_TEM_SOCIEDADE_JURIDICA" MODIFY ("URI_SOCIEDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_TEM_SOCIEDADE_FISICA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SOCIEDADE_FISICA" MODIFY ("URI_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "RFB_TEM_SOCIEDADE_FISICA" MODIFY ("URI_SOCIEDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_TEM_SOCIEDADE_ESTRANGEIRA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SOCIEDADE_ESTRANGEIRA" MODIFY ("URI_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "RFB_TEM_SOCIEDADE_ESTRANGEIRA" MODIFY ("URI_SOCIEDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_TEM_SITUACAO_ESPECIAL
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_SITUACAO_ESPECIAL" MODIFY ("URI_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "RFB_TEM_SITUACAO_ESPECIAL" MODIFY ("URI_SITUACAO_ESPECIAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_TEM_ESTABELECIMENTO
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_ESTABELECIMENTO" MODIFY ("URI_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "RFB_TEM_ESTABELECIMENTO" MODIFY ("URI_ESTABELECIMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_TEM_ATIV_ECONOMICA_SECUNDARIA
--------------------------------------------------------

  ALTER TABLE "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA" MODIFY ("URI_ESTABELECIMENTO" NOT NULL DISABLE);
  ALTER TABLE "RFB_TEM_ATIV_ECONOMICA_SECUNDARIA" MODIFY ("URI_ATIVIDADE_ECONOMICA" NOT NULL DISABLE);
--------------------------------------------------------
--  Constraints for Table RFB_RAZAO_SITUACAO_CADASTRAL
--------------------------------------------------------

  ALTER TABLE "RFB_RAZAO_SITUACAO_CADASTRAL" MODIFY ("URI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_OPCAO_SIMPLES
--------------------------------------------------------

  ALTER TABLE "RFB_OPCAO_SIMPLES" MODIFY ("URI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_OPCAO_MEI
--------------------------------------------------------

  ALTER TABLE "RFB_OPCAO_MEI" MODIFY ("URI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_NATUREZA_LEGAL
--------------------------------------------------------

  ALTER TABLE "RFB_NATUREZA_LEGAL" MODIFY ("URI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_FAIXA_ETARIA
--------------------------------------------------------

  ALTER TABLE "RFB_FAIXA_ETARIA" MODIFY ("URI_FAIXA_ETARIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_ESTABELECIMENTO
--------------------------------------------------------

  ALTER TABLE "RFB_ESTABELECIMENTO" MODIFY ("CNPJ" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_ENDERECO_EXTERIOR
--------------------------------------------------------

  ALTER TABLE "RFB_ENDERECO_EXTERIOR" MODIFY ("URI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_EMPRESA_HOLDING
--------------------------------------------------------

  ALTER TABLE "RFB_EMPRESA_HOLDING" MODIFY ("URI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RFB_EMPRESA
--------------------------------------------------------

  ALTER TABLE "RFB_EMPRESA" MODIFY ("URI" NOT NULL ENABLE);
  ALTER TABLE "RFB_EMPRESA" MODIFY ("CNPJ_RAIZ" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table RFB_ESTABELECIMENTO_EXTERIOR
--------------------------------------------------------

  ALTER TABLE "RFB_ESTABELECIMENTO_EXTERIOR" MODIFY ("URI" NOT NULL ENABLE);