
  CREATE MATERIALIZED VIEW "UFC_SEM"."SAMEAS_CAD_RFB_ESTABELECIMENTO" ("RFB_ID", "CAD_ID")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT rfb.CNPJ AS RFB_ID, cad.INSCRICAO_ESTADUAL AS CAD_ID 
            FROM "RFB_ESTABELECIMENTO" rfb
            INNER JOIN
            "CAD_ESTABELECIMENTO" cad
            ON
            rfb.CNPJ = cad.CNPJ;

  CREATE INDEX "UFC_SEM"."SAMEAS_CAD_RFB_ESTABELECIMENTO_INDEX1" ON "UFC_SEM"."SAMEAS_CAD_RFB_ESTABELECIMENTO" ("RFB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "UFC_SEM"."SAMEAS_CAD_RFB_ESTABELECIMENTO_INDEX2" ON "UFC_SEM"."SAMEAS_CAD_RFB_ESTABELECIMENTO" ("CAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."SAMEAS_CAD_RFB_ESTABELECIMENTO"  IS 'snapshot table for snapshot SAMEAS_CAD_RFB_ESTABELECIMENTO';
