--------------------------------------------------------
--  Arquivo criado - Terça-feira-Junho-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View C115_UNIDADE_CONSUMO_ITEM_CADENDERECO
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UFC_SEM"."C115_UNIDADE_CONSUMO_ITEM_CADENDERECO" ("NUM_TERMINAL_TELEFONICO_CONTA", "CNPJ2", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF", "IE", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF", "DATA_EMISSAO", "MODELO", "PERIODO", "CODIGO_SERVICO_FORNECIMENTO", "QUANTIDADE_PRESTADA_FORNECIDA") AS 
  SELECT mestre.num_terminal_telefonico_conta, 
       controle.cnpj2, 
       destinatario.codigo_identificacao_consumido,
       destinatario.cnpjcpf,
       destinatario.IE,
       destinatario.RAZAO_SOCIAL,
       destinatario.logradouro, 
       destinatario.numero,
       destinatario.complemento,
       destinatario.cep,
       destinatario.bairro,
       destinatario.municipio,
       destinatario.uf,
       mestre.data_emissao,
       controle.modelo,
       controle.periodo,
       item.CODIGO_SERVICO_FORNECIMENTO,
       item.quantidade_prestada_fornecida
FROM APL_C115.controle@"DL_ARMA.SEFAZ.MA.GOV.BR" controle
INNER JOIN APL_C115.mestre@"DL_ARMA.SEFAZ.MA.GOV.BR" mestre ON controle.ID_CONTROLE=mestre.ID_CONTROLE
INNER JOIN APL_C115.destinatario@"DL_ARMA.SEFAZ.MA.GOV.BR" destinatario ON mestre.id_mestre=destinatario.id_mestre
INNER JOIN APL_C115.item@"DL_ARMA.SEFAZ.MA.GOV.BR" item ON mestre.id_mestre=item.id_mestre
WHERE mestre.situacao_documento<>'S' AND controle.ultima_manual2='S' AND mestre.num_terminal_telefonico_conta IS NOT NULL
;
--------------------------------------------------------
--  DDL for View C115_UNIDADE_CONSUMO_CADENDERECO
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UFC_SEM"."C115_UNIDADE_CONSUMO_CADENDERECO" ("NUM_TERMINAL_TELEFONICO_CONTA", "CNPJ2", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF", "IE", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF", "DATA_EMISSAO", "MODELO", "PERIODO") AS 
  (
  SELECT mestre.num_terminal_telefonico_conta, 
       controle.cnpj2, 
       destinatario.codigo_identificacao_consumido,
       destinatario.cnpjcpf,
       destinatario.IE,
       destinatario.RAZAO_SOCIAL,
       destinatario.logradouro, 
       destinatario.numero,
       destinatario.complemento,
       destinatario.cep,
       destinatario.bairro,
       destinatario.municipio,
       destinatario.uf,
       mestre.data_emissao,
       controle.modelo,
       controle.periodo
FROM APL_C115.controle@"DL_ARMA.SEFAZ.MA.GOV.BR" controle
INNER JOIN APL_C115.mestre@"DL_ARMA.SEFAZ.MA.GOV.BR" mestre ON controle.ID_CONTROLE=mestre.ID_CONTROLE
INNER JOIN APL_C115.destinatario@"DL_ARMA.SEFAZ.MA.GOV.BR" destinatario ON mestre.id_mestre=destinatario.id_mestre
WHERE mestre.situacao_documento<>'S' AND controle.ultima_manual2='S' AND mestre.num_terminal_telefonico_conta IS NOT NULL --  controle.periodo = 202105
)
;
--------------------------------------------------------
--  DDL for View C115_ITEM
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UFC_SEM"."C115_ITEM" ("ID_ITEM", "ID_DOCUMENTO", "NUMERO_DOCUMENTO", "DESCRICAO_CLASSIFICACAO", "GRUPO", "NUMERO_ORDEM", "VALOR_TOTAL", "VALOR_DESCONTO", "VALOR_ACRESCIMO", "BASE_CALCULO_ICMS", "VALOR_ICMS", "VALOR_OPERACOES_ISENTAS", "OUTROS_VALORES", "ALIQUOTA", "CFOP", "SITUACAO", "UNIDADE_MEDIDA", "QUANTIDADE_CONTRATADA", "QUANTIDADE_PRESTADA", "SERVICO_FORNECIMENTO", "TIPO") AS 
  (
SELECT ITEM.ID_ITEM AS ID_ITEM,
    ITEM.ID_MESTRE AS ID_DOCUMENTO,
    ITEM.NUMERO AS NUMERO_DOCUMENTO,
    CASE CODIGO_CLASSIFICACAO_ITEM 
    WHEN 101 THEN 'Assinatura de serviços de telefonia'
    WHEN 102 THEN 'Assinatura de serviços de comunicação de dados'
    WHEN 103 THEN 'Assinatura de serviços de TV por Assinatura'
    WHEN 104 THEN 'Assinatura de serviços de provimento à internet'
    WHEN 105 THEN 'Assinatura de outros serviços de multimídia'
    WHEN 199 THEN 'Assinatura de outros serviços'
    WHEN 201 THEN 'Habilitação de serviços de telefonia'
    WHEN 202 THEN 'Habilitação de serviços de comunicação de dados'
    WHEN 203 THEN 'Habilitação de TV por Assinatura'
    WHEN 204 THEN 'Habilitação de serviços de provimento à internet'
    WHEN 205 THEN 'Habilitação de outros serviços multimídia'
    WHEN 299 THEN 'Habilitação de outros serviços'
    WHEN 301 THEN 'Serviço Medido - chamadas locais'
    WHEN 302 THEN 'Serviço Medido - chamadas interurbanas no Estado'
    WHEN 303 THEN 'Serviço Medido - chamadas interurbanas para fora do Estado'
    WHEN 304 THEN 'Serviço Medido - chamadas internacionais'
    WHEN 305 THEN 'Serviço Medido - Números Especiais (0300/0500/0600/0800/etc.)'
    WHEN 306 THEN 'Serviço Medido - comunicação de dados'
    WHEN 307 THEN 'Serviço Medido - chamadas originadas em Roaming'
    WHEN 308 THEN 'Serviço Medido - chamadas recebidas em Roaming'
    WHEN 309 THEN 'Serviço Medido - adicional de chamada'
    WHEN 310 THEN 'Serviço Medido - provimento de acesso à Internet'
    WHEN 311 THEN 'Serviço Medido - pay-per-view (programação TV)'
    WHEN 312 THEN 'Serviço Medido - Mensagem SMS'
    WHEN 313 THEN 'Serviço Medido - Mensagem MMS'
    WHEN 314 THEN 'Serviço Medido - outros mensagens'
    WHEN 315 THEN 'Serviço Medido - serviço multimídia'
    WHEN 399 THEN 'Serviço Medido - outros serviços'
    WHEN 401 THEN 'Cartão Telefônico - Telefonia Fixa'
    WHEN 402 THEN 'Cartão Telefônico - Telefonia Móvel'
    WHEN 403 THEN 'Cartão de Provimento de acesso à internet'
    WHEN 404 THEN 'Ficha Telefônica'
    WHEN 405 THEN 'Recarga de Créditos - Telefonia Fixa'
    WHEN 406 THEN 'Recarga de Créditos - Telefonia Móvel'
    WHEN 407 THEN 'Recarga de Créditos - Provimento de acesso à Internet'
    WHEN 499 THEN 'Outras cobranças realizadas de assinantes de plano serviço pré-pago'
    WHEN 501 THEN 'Serviço Adicional (substituição de número, troca de aparelho, emissão de 2ª via de conta, conta detalhada, etc.)'
    WHEN 502 THEN 'Serviço Facilidades (identificador de chamadas, caixa postal, transferência temporária, não-perturbe, etc.)'
    WHEN 599 THEN 'Outros Serviços'
    WHEN 601 THEN 'Energia Elétrica - Consumo'
    WHEN 602 THEN 'Energia Elétrica - Demanda'
    WHEN 603 THEN 'Energia Elétrica - Serviços (Vistoria de unidade consumidora, Aferição de Medidor, Ligação, Religação, Troca de medidor, etc.)'
    WHEN 604 THEN 'Energia Elétrica - Encargos Emergenciais'
    WHEN 605 THEN 'Tarifa de Uso dos Sistemas de Distribuição de Energia Elétrica - TUSD - Consumidor Cativo'
    WHEN 606 THEN 'Tarifa de Uso dos Sistemas de Distribuição de Energia Elétrica - TUSD - Consumidor Livre'
    WHEN 607 THEN 'Encargos de Conexão'
    WHEN 608 THEN 'Tarifa de Uso dos Sistemas de Transmissão de Energia Elétrica - TUST - Consumidor Cativo'
    WHEN 609 THEN 'Tarifa de Uso dos Sistemas de Transmissão de Energia Elétrica - TUST - Consumidor Livre'
    WHEN 610 THEN 'Subvenção econômica para consumidores da subclasse ¿baixa renda¿'
    WHEN 699 THEN 'Energia Elétrica - Outros'
    WHEN 701 THEN 'de Aparelho Telefônico'
    WHEN 702 THEN 'de Aparelho Identificador de chamadas'
    WHEN 703 THEN 'de Modem'
    WHEN 704 THEN 'de Rack'
    WHEN 705 THEN 'de Sala/Recinto'
    WHEN 706 THEN 'de Roteador'
    WHEN 707 THEN 'de Servidor'
    WHEN 708 THEN 'de Multiplexador'
    WHEN 709 THEN 'de Decodificador/Conversor'
    WHEN 799 THEN 'Outras disponibilizações'
    WHEN 802 THEN 'Cobrança de Seguros'
    WHEN 803 THEN 'Cobrança de Financiamento de Aparelho/Serviços'
    WHEN 804 THEN 'Cobrança de Juros de Mora'
    WHEN 805 THEN 'Cobrança de Multa de Mora'
    WHEN 806 THEN 'Cobrança de Conta de meses anteriores'
    WHEN 807 THEN 'Cobrança de Taxa Iluminação Pública'
    WHEN 808 THEN 'Retenção de ICMS-ST'
    WHEN 899 THEN 'Outras Cobranças'
    WHEN 902 THEN 'Dedução referente ajuste de conta'
    WHEN 903 THEN 'Redutor - Energia Elétrica - Nº 306/2003 (PIS/COFINS/IRPJ/CSLL)'
    WHEN 904 THEN 'Dedução relativa à multa pela interrupção de fornecimento'
    WHEN 905 THEN 'Dedução relativa à distribuição de dividendos Eletrobrás'
    WHEN 906 THEN 'Dedução relativa à subvenção econômica para consumidores da subclasse ¿baixa renda¿'
    WHEN 907 THEN 'Dedução relativa à parcela do valor da operação correspondente ao valor da energia elétrica adquirida de terceiros, quando aplicáveis os termos do Convênio ICMS 77/11.'
    WHEN 999 THEN 'Outras deduções'
    WHEN 1002 THEN 'Serviço não medido de serviços de comunicação de dados'
    WHEN 1003 THEN 'Serviço não medido de serviços de TV por Assinatura'
    WHEN 1004 THEN 'Serviço não medido de serviços de provimento à internet'
    WHEN 1005 THEN 'Serviço não medido de outros serviços de multimídia'
    WHEN 1099 THEN 'Serviço não medido de outros serviços'
    WHEN 1101 THEN 'Interconexão: Detraf, SMS, MMS'
    WHEN 1102 THEN 'Detrat, Transmissão'
    WHEN 1103 THEN 'Roaming'
    WHEN 1104 THEN 'Exploração Industrial de Linha Dedicada - EILD'
    WHEN 1105 THEN 'Lançamento de ICMS proporcional às saídas isentas, não tributadas ou com redução de base de cálculo (§ 1º, Cláusula terceira, Convênio ICMS17/2013)'
    WHEN 1106 THEN 'Lançamento de ICMS proporcional às cessões de meio destinadas a
consumo próprio (§ 1º Cláusula terceira, Convênio ICMS 17/2013)'
    WHEN 1107 THEN 'Lançamento de ICMS complementar, na condição de responsável tributário (§ 2º, Cláusula terceira, Convênio 17/2013)'
    WHEN 1199 THEN 'Outras Cessões de Meios de Rede'
    END AS DESCRICAO_CLASSIFICACAO,
    CASE  
    WHEN CODIGO_CLASSIFICACAO_ITEM > 100 AND CODIGO_CLASSIFICACAO_ITEM < 201 THEN 'Assinatura' 
    WHEN CODIGO_CLASSIFICACAO_ITEM > 200 AND CODIGO_CLASSIFICACAO_ITEM < 301 THEN 'Habilitação'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 300 AND CODIGO_CLASSIFICACAO_ITEM < 401 THEN 'Serviço Médio'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 400 AND CODIGO_CLASSIFICACAO_ITEM < 501 THEN 'Serviço Pré-Pago'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 500 AND CODIGO_CLASSIFICACAO_ITEM < 601 THEN 'Outros Serviços'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 600 AND CODIGO_CLASSIFICACAO_ITEM < 701 THEN 'Energia Elétrica'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 700 AND CODIGO_CLASSIFICACAO_ITEM < 801 THEN 'Disponibilização de Meios ou Equipamentos'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 800 AND CODIGO_CLASSIFICACAO_ITEM < 901 THEN 'Deduções'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 900 AND CODIGO_CLASSIFICACAO_ITEM < 1001 THEN 'Serviço não medido'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 1000 AND CODIGO_CLASSIFICACAO_ITEM < 1101 THEN 'Cessão de Meios de Rede'
    WHEN CODIGO_CLASSIFICACAO_ITEM > 1100 AND CODIGO_CLASSIFICACAO_ITEM < 2000 THEN 'Serviço Médio'
    END AS GRUPO,
    ITEM.ITEM AS NUMERO_ORDEM,
    ITEM.TOTAL AS VALOR_TOTAL,
    ITEM.DESCONTOS_REDUTORES AS VALOR_DESCONTO,
    ITEM.ACRESCIMOS_DESPESAS_ACESSORIAS AS VALOR_ACRESCIMO,
    ITEM.BC_ICMS AS BASE_CALCULO_ICMS,
    ITEM.ICMS AS VALOR_ICMS,
    ITEM.OPERACOES_ISENTAS_NAO_TRIBUT AS VALOR_OPERACOES_ISENTAS,
    ITEM.OUTROS_VALORES AS OUTROS_VALORES,
    ITEM.ALIQUOTA_ICMS AS ALIQUOTA,
    ITEM.CFOP AS CFOP,
    CASE ITEM.SITUACAO
        WHEN 'S' THEN 'Cancelado'
        WHEN 'R' THEN 'Substituido'
        WHEN 'N' THEN 'Normal'
    END AS SITUACAO,
    ITEM.UNIDADE AS UNIDADE_MEDIDA,
    ITEM.QUANTIDADE_CONTRATADA AS QUANTIDADE_CONTRATADA,
    ITEM.QUANTIDADE_PRESTADA_FORNECIDA AS QUANTIDADE_PRESTADA,
    CODIGO_SERVICO_FORNECIMENTO AS SERVICO_FORNECIMENTO,
    CASE WHEN MODELO = 6 THEN 'FORNECIMENTO' ELSE 'SERVIÇO' END AS TIPO
    FROM APL_C115.ITEM@dl_arma ITEM
)
WITH READ ONLY
;
--------------------------------------------------------
--  DDL for View C115_ENDERECO
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UFC_SEM"."C115_ENDERECO" ("CNPJ_CPF", "INSCRICAO_ESTADUAL", "UF", "CIDADE", "BAIRRO", "LOGRADOURO", "CEP", "NUMERO", "COMPLEMENTO", "TIPO") AS 
  (
SELECT DISTINCT
    TO_CHAR(controle.CNPJ) AS CNPJ_CPF,
    controle.IE AS INSCRICAO_ESTADUAL,
    controle.UF AS UF,
    controle.MUNICIPIO AS CIDADE,
    controle.BAIRRO AS BAIRRO,
    controle.ENDERECO AS LOGRADOURO,
    controle.CEP AS CEP,
    '' AS NUMERO,
    '' AS COMPLEMENTO,
    'PROVEDOR' AS TIPO
    FROM APL_C115.CONTROLE@dl_arma controle 
    UNION ALL
    SELECT DISTINCT 
    TO_CHAR(destinatario.CNPJCPF) AS CNPJ_CPF,
    DESTINATARIO.IE AS INSCRICAO_ESTADUAL,
    destinatario.UF AS UF,
    destinatario.MUNICIPIO AS CIDADE,
    destinatario.BAIRRO AS BAIRRO,
    destinatario.LOGRADOURO AS LOGRADOURO,
    TO_CHAR(destinatario.CEP) AS CEP,
    destinatario.NUMERO AS NUMERO,
    destinatario.COMPLEMENTO AS COMPLEMENTO,
    'CONSUMIDOR' AS TIPO
    FROM APL_C115.DESTINATARIO@dl_arma destinatario 
)
WITH READ ONLY
;
--------------------------------------------------------
--  DDL for View C115_DOCUMENTO_FISCAL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "UFC_SEM"."C115_DOCUMENTO_FISCAL" ("ID_DOCUMENTO", "NUMERO_DOCUMENTO", "ID_UNIDADE_CONSUMO", "ID_CONSUMIDOR", "DATA_EMISSAO", "ANO_APURACAO", "MES_APURACAO", "CODIGO_AUTENTICACAO", "OUTROS_VALORES", "VALOR_TOTAL", "VALOR_OPERACOES_ISENTAS", "VALOR_ICMS", "BASE_CALCULO_ICMS", "SERIE", "MODELO", "EMITENTE") AS 
  (
    SELECT MESTRE.ID_MESTRE AS ID_DOCUMENTO,
    MESTRE.NUMERO AS NUMERO_DOCUMENTO,
    MESTRE.NUM_TERMINAL_TELEFONICO_CONTA AS ID_UNIDADE_CONSUMO,
    MESTRE.CODIGO_IDENTIFICACAO_CONSUMIDO AS ID_CONSUMIDOR,
    MESTRE.DATA_EMISSAO,
    SUBSTR(MESTRE.ANO_MES_REFERENCIA_APURACAO,0,3) AS ANO_APURACAO,
    SUBSTR(MESTRE.ANO_MES_REFERENCIA_APURACAO,2,5) AS MES_APURACAO,
    MESTRE.COD_AUTENTICACAO_DIGITAL_DOC AS CODIGO_AUTENTICACAO,
    MESTRE.OUTROS_VALORES AS OUTROS_VALORES,
    MESTRE.VALOR_TOTAL AS VALOR_TOTAL,
    MESTRE.OPERACOES_INSENTA_NAO_TRIBUT AS VALOR_OPERACOES_ISENTAS,
    MESTRE.ICMS_DESTACADO AS VALOR_ICMS,
    MESTRE.BC_ICMS BASE_CALCULO_ICMS,
    MESTRE.SERIE AS SERIE,
    MESTRE.MODELO AS MODELO,
    mestre.CNPJCPF AS EMITENTE
    FROM APL_C115.MESTRE@dl_arma mestre
    
)
WITH READ ONLY
;
--------------------------------------------------------
--  DDL for Materialized View C115_CONSUMIDOR
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_CONSUMIDOR" ("CNPJCPF", "NOME", "INSCRICAO_ESTADUAL", "TIPO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT mestre.CNPJCPF AS CNPJCPF, 
       max(mestre.RAZAO_SOCIAL) keep (dense_rank last order by mestre.ID_MESTRE) as NOME,
       max(mestre.IE) keep (dense_rank last order by mestre.ID_MESTRE) as INSCRICAO_ESTADUAL,
       CASE WHEN LENGTH(CNPJCPF) >= 12 THEN 'PJ' ELSE 'PF' END AS TIPO 
FROM APL_C115.mestre@dl_arma mestre
INNER JOIN APL_C115.controle@dl_arma controle ON controle.ID_CONTROLE=mestre.ID_CONTROLE
WHERE mestre.situacao_documento<>'S' AND controle.ultima_manual2='S'
AND mestre.CNPJCPF IS NOT NULL
--AND controle.periodo IN
  --    ( SELECT max(PERIODO) from APL_C115.controle@dl_arma WHERE ultima_manual2='S' )
GROUP BY mestre.CNPJCPF;

  CREATE INDEX "UFC_SEM"."C115_CONSUMIDOR_INDEX2" ON "UFC_SEM"."C115_CONSUMIDOR" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_CONSUMIDOR_INDEX3" ON "UFC_SEM"."C115_CONSUMIDOR" ("INSCRICAO_ESTADUAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE UNIQUE INDEX "UFC_SEM"."C115_CONSUMIDOR_INDEX1" ON "UFC_SEM"."C115_CONSUMIDOR" ("CNPJCPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_CONSUMIDOR"  IS 'snapshot table for snapshot UFC_SEM.C115_CONSUMIDOR';
--------------------------------------------------------
--  DDL for Materialized View C115_PROVEDOR
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_PROVEDOR" ("CNPJ", "RAZAO_SOCIAL", "INSCRICAO_ESTADUAL", "INSCRICAO_ESTADUAL_NUM", "TELEFONE", "EMAIL", "ENDERECO", "BAIRRO", "CEP", "UF", "MUNICIPIO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT TO_CHAR(CONTROLE.CNPJ2) AS CNPJ,
        max(controle.RAZAO_SOCIAL) keep (dense_rank last order by controle.ID_CONTROLE) as RAZAO_SOCIAL,
        max(CONTROLE.IE) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as INSCRICAO_ESTADUAL,
        max(CONTROLE.IE2) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as INSCRICAO_ESTADUAL_NUM,
        max(CONTROLE.TELEFONE) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as TELEFONE,
        max(CONTROLE.EMAIL) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as EMAIL,
        max(CONTROLE.ENDERECO) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as ENDERECO,
        max(CONTROLE.BAIRRO) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as BAIRRO,
        max(CONTROLE.CEP) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as CEP,
        max(CONTROLE.UF) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as UF,
        max(CONTROLE.MUNICIPIO) keep (dense_rank last order by CONTROLE.ID_CONTROLE) as MUNICIPIO
FROM APL_C115.controle@dl_arma controle
GROUP BY controle.cnpj2;

  CREATE INDEX "UFC_SEM"."C115_PROVEDOR_INDEX1" ON "UFC_SEM"."C115_PROVEDOR" ("CNPJ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_PROVEDOR_INDEX2" ON "UFC_SEM"."C115_PROVEDOR" ("RAZAO_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_PROVEDOR_INDEX3" ON "UFC_SEM"."C115_PROVEDOR" ("INSCRICAO_ESTADUAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_PROVEDOR_INDEX4" ON "UFC_SEM"."C115_PROVEDOR" ("INSCRICAO_ESTADUAL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_PROVEDOR"  IS 'snapshot table for snapshot UFC_SEM.C115_PROVEDOR';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_COMUNICACAO_MAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("ID_UNIDADE", "ROTULO", "CNPJ_PROVEDOR", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "INSCRICAO_ESTADUAL", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF", "TIPO_ASSINANTE", "TIPO_UTILIZACAO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT CASE WHEN mestre.num_terminal_telefonico_conta IS NOT NULL THEN MAX(mestre.num_terminal_telefonico_conta) ELSE MAX(mestre.codigo_identificacao_consumido) END AS ID_UNIDADE, 
       max(CONCAT(CONCAT(CONCAT(CONCAT(mestre.num_terminal_telefonico_conta,'-'),destinatario.cnpjcpf),'-'),controle.cnpj2)) AS ROTULO,
       controle.cnpj2 AS cnpj_provedor, 
       max(destinatario.codigo_identificacao_consumido) keep (dense_rank last order by mestre.data_emissao) as codigo_identificacao_consumidor,
       max(destinatario.cnpjcpf) keep (dense_rank last order by mestre.data_emissao) as cnpjcpf_consumidor,
       max(destinatario.IE) keep (dense_rank last order by mestre.data_emissao) as inscricao_estadual,
       max(destinatario.RAZAO_SOCIAL) keep (dense_rank last order by mestre.data_emissao) as razao_social,
       max(destinatario.logradouro) keep (dense_rank last order by mestre.data_emissao) as logradouro, 
       max(destinatario.numero) keep (dense_rank last order by mestre.data_emissao) as numero,
       max(destinatario.complemento) keep (dense_rank last order by mestre.data_emissao) as complemento,
       max(destinatario.cep) keep (dense_rank last order by mestre.data_emissao) as cep,
       max(destinatario.bairro) keep (dense_rank last order by mestre.data_emissao) as bairro,
       max(destinatario.municipio) keep (dense_rank last order by mestre.data_emissao) as municipio,
       max(destinatario.uf) keep (dense_rank last order by mestre.data_emissao) as uf,
       max(CASE mestre.CLASSE_CONSUMO_TIPO_ASSINANTE 
        WHEN 1 THEN 'Comercial-Industrial'
        WHEN 2 THEN 'Poder_Público'
        WHEN 3 THEN 'Residencial-Pessoa_Física'
        WHEN 4 THEN 'Público'
        WHEN 5 THEN 'Semi_Público'
        ELSE 'Outros'
        END) keep (dense_rank last order by mestre.data_emissao) as TIPO_ASSINANTE,
        max(CASE FASE_TIPO_UTILIZACAO 
        WHEN 1 THEN 'Telefonia'
        WHEN 2 THEN 'Comunicacao_Dados'
        WHEN 3 THEN 'TV_Assinatura'
        WHEN 4 THEN 'Provimento_Acesso_Internet'
        WHEN 5 THEN 'Multimidia'
        WHEN 6 THEN 'Outros'
        END) keep (dense_rank last order by mestre.data_emissao) as TIPO_UTILIZACAO 
FROM APL_C115.controle@DL_ARMA controle
INNER JOIN APL_C115.mestre@DL_ARMA mestre ON controle.ID_CONTROLE=mestre.ID_CONTROLE
INNER JOIN APL_C115.destinatario@DL_ARMA destinatario ON mestre.id_mestre=destinatario.id_mestre
WHERE 
      controle.modelo=21 AND 
      mestre.situacao_documento<>'S' 
      AND controle.periodo IN
      ( SELECT max(PERIODO) from APL_C115.controle@DL_ARMA WHERE modelo = 21 )
GROUP BY mestre.num_terminal_telefonico_conta, controle.cnpj2;

  CREATE UNIQUE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX1" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("ID_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX10" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("COMPLEMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX11" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("CEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX12" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("BAIRRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX13" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX14" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("UF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX15" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("TIPO_ASSINANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX16" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("TIPO_UTILIZACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX2" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX3" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("CNPJ_PROVEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX4" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("CODIGO_IDENTIFICACAO_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX5" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("CNPJCPF_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX6" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("INSCRICAO_ESTADUAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX7" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("RAZAO_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX8" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("LOGRADOURO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_INDEX9" ON "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_COMUNICACAO_MAT';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_COMUNICACAO_MAT_CADENDERECO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_CADENDERECO" ("ID_UNIDADE", "CNPJ_PROVEDOR", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "INSCRICAO_ESTADUAL", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT C115UC.NUM_TERMINAL_TELEFONICO_CONTA AS ID_UNIDADE, C115UC.CNPJ2 AS cnpj_provedor,
       max(C115UC.CODIGO_IDENTIFICACAO_CONSUMIDOR) keep (dense_rank last order by C115UC.data_emissao) as codigo_identificacao_consumidor,
       max(C115UC.cnpjcpf) keep (dense_rank last order by C115UC.data_emissao) as cnpjcpf_consumidor,
       max(C115UC.IE) keep (dense_rank last order by C115UC.data_emissao) as inscricao_estadual,
       max(C115UC.RAZAO_SOCIAL) keep (dense_rank last order by C115UC.data_emissao) as razao_social,
       max(C115UC.logradouro) keep (dense_rank last order by C115UC.data_emissao) as logradouro,
       max(C115UC.numero) keep (dense_rank last order by C115UC.data_emissao) as numero,
       max(C115UC.complemento) keep (dense_rank last order by C115UC.data_emissao) as complemento,
       max(C115UC.cep) keep (dense_rank last order by C115UC.data_emissao) as cep,
       max(C115UC.bairro) keep (dense_rank last order by C115UC.data_emissao) as bairro,
       max(C115UC.municipio) keep (dense_rank last order by C115UC.data_emissao) as municipio,
       max(C115UC.uf) keep (dense_rank last order by C115UC.data_emissao) as uf
FROM C115_UNIDADE_CONSUMO_CADENDERECO C115UC
WHERE C115UC.MODELO=21 AND C115UC.PERIODO >= 202201 AND C115UC.PERIODO <= 202201
GROUP BY C115UC.NUM_TERMINAL_TELEFONICO_CONTA, C115UC.CNPJ2;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_COMUNICACAO_MAT_CADENDERECO"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_COMUNICACAO_MAT_CADENDERECO';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_CONSUMO_MAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT" ("ID_UNIDADE", "ROTULO", "CNPJ_PROVEDOR", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "LOGRADOURO", "NUMERO", "BAIRRO", "CEP", "UF", "MUNICIPIO", "COMPLEMENTO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT ID_UNIDADE,
    CONCAT(CONCAT(CONCAT(CONCAT(codigo_identificacao_consumidor,'-'),cnpjcpf_consumidor),'-'),cnpj_provedor) AS ROTULO,
    cnpj_provedor,
    codigo_identificacao_consumidor,
    cnpjcpf_consumidor,
    LOGRADOURO,
    NUMERO,
    BAIRRO,
    CEP,
    UF,
    MUNICIPIO,
    COMPLEMENTO
    FROM C115_UNIDADE_ENERGIA_ELETRICA_MAT_
    UNION
    SELECT DISTINCT ID_UNIDADE,
    CONCAT(CONCAT(CONCAT(CONCAT(codigo_identificacao_consumidor,'-'),cnpjcpf_consumidor),'-'),cnpj_provedor) AS ROTULO,
    cnpj_provedor,
    codigo_identificacao_consumidor,
    cnpjcpf_consumidor,
    LOGRADOURO,
    NUMERO,
    BAIRRO,
    CEP,
    UF,
    MUNICIPIO,
    COMPLEMENTO
    FROM C115_UNIDADE_COMUNICACAO_MAT
    UNION
    SELECT DISTINCT ID_UNIDADE,
    CONCAT(CONCAT(CONCAT(CONCAT(codigo_identificacao_consumidor,'-'),cnpjcpf_consumidor),'-'),cnpj_provedor) AS ROTULO,
    cnpj_provedor,
    codigo_identificacao_consumidor,
    cnpjcpf_consumidor,
    LOGRADOURO,
    NUMERO,
    BAIRRO,
    CEP,
    UF,
    MUNICIPIO,
    COMPLEMENTO
    FROM C115_UNIDADE_TELECOMUNICACAO_MAT;

  CREATE INDEX "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT_INDEX2" ON "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT" ("ROTULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT_INDEX3" ON "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT" ("CNPJ_PROVEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT_INDEX4" ON "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT" ("CODIGO_IDENTIFICACAO_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT_INDEX5" ON "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT" ("CNPJCPF_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE UNIQUE INDEX "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT_INDEX1" ON "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT" ("ID_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_CONSUMO_MAT"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_CONSUMO_MAT';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_ENERGIA_ELETRICA_MAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT" ("ID_UNIDADE", "CNPJ_PROVEDOR", "ROTULO", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "INSCRICAO_ESTADUAL", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF", "GRUPO_TENSAO", "CLASSE_CONSUMO", "FASE", "CONSUMO_MES")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT mestre.num_terminal_telefonico_conta AS ID_UNIDADE, 
controle.cnpj2 AS cnpj_provedor , 
       max(CONCAT(CONCAT(CONCAT(CONCAT(mestre.num_terminal_telefonico_conta,'-'),destinatario.cnpjcpf),'-'),controle.cnpj2)) AS ROTULO,
       max(destinatario.codigo_identificacao_consumido) keep (dense_rank last order by mestre.data_emissao) as codigo_identificacao_consumidor,
       max(destinatario.cnpjcpf) keep (dense_rank last order by mestre.data_emissao) as cnpjcpf_consumidor,
       max(destinatario.IE) keep (dense_rank last order by mestre.data_emissao) as inscricao_estadual,
       max(destinatario.RAZAO_SOCIAL) keep (dense_rank last order by mestre.data_emissao) as razao_social,
       max(destinatario.logradouro) keep (dense_rank last order by mestre.data_emissao) as logradouro, 
       max(destinatario.numero) keep (dense_rank last order by mestre.data_emissao) as numero,
       max(destinatario.complemento) keep (dense_rank last order by mestre.data_emissao) as complemento,
       max(destinatario.cep) keep (dense_rank last order by mestre.data_emissao) as cep,
       max(destinatario.bairro) keep (dense_rank last order by mestre.data_emissao) as bairro,
       max(destinatario.municipio) keep (dense_rank last order by mestre.data_emissao) as municipio,
       max(destinatario.uf) keep (dense_rank last order by mestre.data_emissao) as uf,
       max(mestre.GRUPO_TENSAO) keep (dense_rank last order by mestre.data_emissao) as GRUPO_TENSAO,
       max(mestre.CLASSE_CONSUMO_TIPO_ASSINANTE) keep (dense_rank last order by mestre.data_emissao) as CLASSE_CONSUMO,
       max(mestre.FASE_TIPO_UTILIZACAO) keep (dense_rank last order by mestre.data_emissao) as FASE,
       sum(item.quantidade_prestada_fornecida) AS CONSUMO_MES
FROM APL_C115.controle@DL_ARMA controle
INNER JOIN APL_C115.mestre@DL_ARMA mestre ON controle.ID_CONTROLE=mestre.ID_CONTROLE
INNER JOIN APL_C115.destinatario@DL_ARMA destinatario ON mestre.id_mestre=destinatario.id_mestre
INNER JOIN APL_C115.item@DL_ARMA item ON mestre.id_mestre=item.id_mestre
WHERE controle.modelo=6 AND 
      mestre.situacao_documento<>'S' AND controle.ultima_manual2='S'  AND item.CODIGO_SERVICO_FORNECIMENTO='01000020'
      AND controle.periodo IN
      ( SELECT max(PERIODO) from APL_C115.controle@DL_ARMA WHERE ultima_manual2='S' AND modelo = 6 )
GROUP BY mestre.num_terminal_telefonico_conta, controle.cnpj2;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_ENERGIA_ELETRICA_MAT';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_ENERGIA_ELETRICA_MAT_
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("ID_UNIDADE", "CNPJ_PROVEDOR", "ROTULO", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "INSCRICAO_ESTADUAL", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF", "GRUPO_TENSAO", "CLASSE_CONSUMO", "FASE", "CONSUMO_MES")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT mestre.num_terminal_telefonico_conta AS ID_UNIDADE, 
controle.cnpj2 AS cnpj_provedor , 
       max(CONCAT(CONCAT(CONCAT(CONCAT(mestre.num_terminal_telefonico_conta,'-'),destinatario.cnpjcpf),'-'),controle.cnpj2)) AS ROTULO,
       max(destinatario.codigo_identificacao_consumido) keep (dense_rank last order by mestre.data_emissao) as codigo_identificacao_consumidor,
       max(destinatario.cnpjcpf) keep (dense_rank last order by mestre.data_emissao) as cnpjcpf_consumidor,
       max(destinatario.IE) keep (dense_rank last order by mestre.data_emissao) as inscricao_estadual,
       max(destinatario.RAZAO_SOCIAL) keep (dense_rank last order by mestre.data_emissao) as razao_social,
       max(destinatario.logradouro) keep (dense_rank last order by mestre.data_emissao) as logradouro, 
       max(destinatario.numero) keep (dense_rank last order by mestre.data_emissao) as numero,
       max(destinatario.complemento) keep (dense_rank last order by mestre.data_emissao) as complemento,
       max(destinatario.cep) keep (dense_rank last order by mestre.data_emissao) as cep,
       max(destinatario.bairro) keep (dense_rank last order by mestre.data_emissao) as bairro,
       max(destinatario.municipio) keep (dense_rank last order by mestre.data_emissao) as municipio,
       max(destinatario.uf) keep (dense_rank last order by mestre.data_emissao) as uf,
       max(mestre.GRUPO_TENSAO) keep (dense_rank last order by mestre.data_emissao) as GRUPO_TENSAO,
       max(mestre.CLASSE_CONSUMO_TIPO_ASSINANTE) keep (dense_rank last order by mestre.data_emissao) as CLASSE_CONSUMO,
       max(mestre.FASE_TIPO_UTILIZACAO) keep (dense_rank last order by mestre.data_emissao) as FASE,
       sum(item.quantidade_prestada_fornecida) AS CONSUMO_MES
FROM APL_C115.controle@dl_arma controle
INNER JOIN APL_C115.mestre@dl_arma mestre ON controle.ID_CONTROLE=mestre.ID_CONTROLE
INNER JOIN APL_C115.destinatario@dl_arma destinatario ON mestre.id_mestre=destinatario.id_mestre
INNER JOIN APL_C115.item@dl_arma item ON mestre.id_mestre=item.id_mestre
WHERE controle.modelo=6 AND 
      mestre.situacao_documento<>'S' AND controle.ultima_manual2='S'  AND item.CODIGO_SERVICO_FORNECIMENTO='01000020'
      AND controle.periodo IN
      ( SELECT max(PERIODO) from APL_C115.controle@dl_arma WHERE ultima_manual2='S' AND modelo = 6 )
GROUP BY mestre.num_terminal_telefonico_conta, controle.cnpj2;

  CREATE INDEX "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT__INDEX2" ON "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("CNPJ_PROVEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT__INDEX3" ON "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("CNPJCPF_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT__INDEX4" ON "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("CODIGO_IDENTIFICACAO_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT__INDEX5" ON "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("INSCRICAO_ESTADUAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT__INDEX6" ON "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("RAZAO_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT__INDEX7" ON "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("GRUPO_TENSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE UNIQUE INDEX "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT__INDEX1" ON "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_" ("ID_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_ENERGIA_ELETRICA_MAT_"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_ENERGIA_ELETRICA_MAT_';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_ENERGIA_MAT_CADENDERECO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_ENERGIA_MAT_CADENDERECO" ("ID_UNIDADE", "CNPJ_PROVEDOR", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "INSCRICAO_ESTADUAL", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF", "CONSUMO_MES")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT C115UC.NUM_TERMINAL_TELEFONICO_CONTA AS ID_UNIDADE, C115UC.CNPJ2 AS cnpj_provedor,
       max(C115UC.CODIGO_IDENTIFICACAO_CONSUMIDOR) keep (dense_rank last order by C115UC.data_emissao) as codigo_identificacao_consumidor,
       max(C115UC.cnpjcpf) keep (dense_rank last order by C115UC.data_emissao) as cnpjcpf_consumidor,
       max(C115UC.IE) keep (dense_rank last order by C115UC.data_emissao) as inscricao_estadual,
       max(C115UC.RAZAO_SOCIAL) keep (dense_rank last order by C115UC.data_emissao) as razao_social,
       max(C115UC.logradouro) keep (dense_rank last order by C115UC.data_emissao) as logradouro,
       max(C115UC.numero) keep (dense_rank last order by C115UC.data_emissao) as numero,
       max(C115UC.complemento) keep (dense_rank last order by C115UC.data_emissao) as complemento,
       max(C115UC.cep) keep (dense_rank last order by C115UC.data_emissao) as cep,
       max(C115UC.bairro) keep (dense_rank last order by C115UC.data_emissao) as bairro,
       max(C115UC.municipio) keep (dense_rank last order by C115UC.data_emissao) as municipio,
       max(C115UC.uf) keep (dense_rank last order by C115UC.data_emissao) as uf,
       sum(C115UC.quantidade_prestada_fornecida) AS CONSUMO_MES
FROM C115_UNIDADE_CONSUMO_ITEM_CADENDERECO C115UC
WHERE C115UC.MODELO=6 AND C115UC.CODIGO_SERVICO_FORNECIMENTO='01000020' AND C115UC.PERIODO >= 202201 AND C115UC.PERIODO <= 202201
GROUP BY C115UC.NUM_TERMINAL_TELEFONICO_CONTA, C115UC.CNPJ2;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_ENERGIA_MAT_CADENDERECO"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_ENERGIA_MAT_CADENDERECO';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_TELECOMUNICACAO_MAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT" ("ID_UNIDADE", "ROTULO", "CNPJ_PROVEDOR", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "INSCRICAO_ESTADUAL", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF", "TIPO_ASSINANTE", "TIPO_UTILIZACAO", "CONSUMO_MES")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM"   NO INMEMORY 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT DISTINCT CONCAT(CONCAT(CONCAT(CONCAT(mestre.num_terminal_telefonico_conta,'-'),destinatario.cnpjcpf),'-'),controle.cnpj2) AS ID_UNIDADE, 
      max(CONCAT(CONCAT(CONCAT(CONCAT(mestre.num_terminal_telefonico_conta,'-'),destinatario.cnpjcpf),'-'),controle.cnpj2)) AS ROTULO,
       controle.cnpj2 AS cnpj_provedor, 
       max(destinatario.codigo_identificacao_consumido) keep (dense_rank last order by mestre.data_emissao) as codigo_identificacao_consumidor,
       max(destinatario.cnpjcpf) keep (dense_rank last order by mestre.data_emissao) as cnpjcpf_consumidor,
       max(destinatario.IE) keep (dense_rank last order by mestre.data_emissao) as inscricao_estadual,
       max(destinatario.RAZAO_SOCIAL) keep (dense_rank last order by mestre.data_emissao) as razao_social,
       max(destinatario.logradouro) keep (dense_rank last order by mestre.data_emissao) as logradouro, 
       max(destinatario.numero) keep (dense_rank last order by mestre.data_emissao) as numero,
       max(destinatario.complemento) keep (dense_rank last order by mestre.data_emissao) as complemento,
       max(destinatario.cep) keep (dense_rank last order by mestre.data_emissao) as cep,
       max(destinatario.bairro) keep (dense_rank last order by mestre.data_emissao) as bairro,
       max(destinatario.municipio) keep (dense_rank last order by mestre.data_emissao) as municipio,
       max(destinatario.uf) keep (dense_rank last order by mestre.data_emissao) as uf,
       max(CASE mestre.CLASSE_CONSUMO_TIPO_ASSINANTE 
        WHEN 1 THEN 'Comercial-Industrial'
        WHEN 2 THEN 'Poder_Público'
        WHEN 3 THEN 'Residencial-Pessoa_Física'
        WHEN 4 THEN 'Público'
        WHEN 5 THEN 'Semi_Público'
        ELSE 'Outros'
        END) keep (dense_rank last order by mestre.data_emissao) as TIPO_ASSINANTE,
        max(CASE mestre.FASE_TIPO_UTILIZACAO 
        WHEN 1 THEN 'Telefonia'
        WHEN 2 THEN 'Comunicacao_Dados'
        WHEN 3 THEN 'TV_Assinatura'
        WHEN 4 THEN 'Provimento_Acesso_Internet'
        WHEN 5 THEN 'Multimidia'
        WHEN 6 THEN 'Outros'
        END) keep (dense_rank last order by mestre.data_emissao) as TIPO_UTILIZACAO,
        sum(item.quantidade_prestada_fornecida) AS CONSUMO_MES
FROM APL_C115.controle@dl_arma controle
INNER JOIN APL_C115.mestre@dl_arma mestre ON controle.ID_CONTROLE=mestre.ID_CONTROLE
INNER JOIN APL_C115.destinatario@dl_arma destinatario ON mestre.id_mestre=destinatario.id_mestre
INNER JOIN APL_C115.item@dl_arma item ON mestre.id_mestre=item.id_mestre
WHERE controle.modelo=22 AND 
      mestre.situacao_documento<>'S' AND controle.ultima_manual2='S'
      AND mestre.num_terminal_telefonico_conta IS NOT NULL
      AND controle.periodo IN
      ( SELECT max(PERIODO) from APL_C115.controle@dl_arma WHERE ultima_manual2='S' AND modelo = 22 )
GROUP BY CONCAT(CONCAT(CONCAT(CONCAT(mestre.num_terminal_telefonico_conta,'-'),destinatario.cnpjcpf),'-'),controle.cnpj2), controle.cnpj2;

  CREATE INDEX "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_INDEX2" ON "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT" ("CNPJ_PROVEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_INDEX3" ON "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT" ("CODIGO_IDENTIFICACAO_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_INDEX4" ON "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT" ("CNPJCPF_CONSUMIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_INDEX5" ON "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT" ("INSCRICAO_ESTADUAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE INDEX "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_INDEX6" ON "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT" ("RAZAO_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
  CREATE UNIQUE INDEX "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_INDEX1" ON "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT" ("ID_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_TELECOMUNICACAO_MAT';
--------------------------------------------------------
--  DDL for Materialized View C115_UNIDADE_TELECOMUNICACAO_MAT_CADENDERECO
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_CADENDERECO" ("ID_UNIDADE", "CNPJ_PROVEDOR", "CODIGO_IDENTIFICACAO_CONSUMIDOR", "CNPJCPF_CONSUMIDOR", "INSCRICAO_ESTADUAL", "RAZAO_SOCIAL", "LOGRADOURO", "NUMERO", "COMPLEMENTO", "CEP", "BAIRRO", "MUNICIPIO", "UF")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT C115UC.NUM_TERMINAL_TELEFONICO_CONTA AS ID_UNIDADE, C115UC.CNPJ2 AS cnpj_provedor,
       max(C115UC.CODIGO_IDENTIFICACAO_CONSUMIDOR) keep (dense_rank last order by C115UC.data_emissao) as codigo_identificacao_consumidor,
       max(C115UC.cnpjcpf) keep (dense_rank last order by C115UC.data_emissao) as cnpjcpf_consumidor,
       max(C115UC.IE) keep (dense_rank last order by C115UC.data_emissao) as inscricao_estadual,
       max(C115UC.RAZAO_SOCIAL) keep (dense_rank last order by C115UC.data_emissao) as razao_social,
       max(C115UC.logradouro) keep (dense_rank last order by C115UC.data_emissao) as logradouro,
       max(C115UC.numero) keep (dense_rank last order by C115UC.data_emissao) as numero,
       max(C115UC.complemento) keep (dense_rank last order by C115UC.data_emissao) as complemento,
       max(C115UC.cep) keep (dense_rank last order by C115UC.data_emissao) as cep,
       max(C115UC.bairro) keep (dense_rank last order by C115UC.data_emissao) as bairro,
       max(C115UC.municipio) keep (dense_rank last order by C115UC.data_emissao) as municipio,
       max(C115UC.uf) keep (dense_rank last order by C115UC.data_emissao) as uf
FROM C115_UNIDADE_CONSUMO_CADENDERECO C115UC
WHERE C115UC.MODELO=22 AND C115UC.PERIODO >= 202201 AND C115UC.PERIODO <= 202201
GROUP BY C115UC.NUM_TERMINAL_TELEFONICO_CONTA, C115UC.CNPJ2;

   COMMENT ON MATERIALIZED VIEW "UFC_SEM"."C115_UNIDADE_TELECOMUNICACAO_MAT_CADENDERECO"  IS 'snapshot table for snapshot UFC_SEM.C115_UNIDADE_TELECOMUNICACAO_MAT_CADENDERECO';
