--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Setembro-30-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES
--------------------------------------------------------

  CREATE TABLE "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES" 
   (	"ID_ATIVIDADE_ECONOMICA" VARCHAR2(200 BYTE), 
	"ANO_VALIDACAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_ATIVIDADES_ISENTAS
--------------------------------------------------------

  CREATE TABLE "IBGE_ATIVIDADES_ISENTAS" 
   (	"CNAE" VARCHAR2(30 BYTE), 
	"URI" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_ATIVIDADES_PERMITIDAS_MEI
--------------------------------------------------------

  CREATE TABLE "IBGE_ATIVIDADES_PERMITIDAS_MEI" 
   (	"ID_ATIVIDADE_ECONOMICA" VARCHAR2(200 BYTE), 
	"ANO_VALIDACAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_CLASSE_CNAE
--------------------------------------------------------

  CREATE TABLE "IBGE_CLASSE_CNAE" 
   (	"ID_CLASSE_CNAE" VARCHAR2(200 BYTE), 
	"CODIGO_CLASSE" VARCHAR2(100 BYTE), 
	"DENOMINACAO" VARCHAR2(200 BYTE), 
	"ID_GRUPO_CNAE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_DIVISAO_CNAE
--------------------------------------------------------

  CREATE TABLE "IBGE_DIVISAO_CNAE" 
   (	"ID_DIVISAO_CNAE" VARCHAR2(200 BYTE), 
	"CODIGO_DIVISAO" VARCHAR2(100 BYTE), 
	"DENOMINACAO" VARCHAR2(200 BYTE), 
	"ID_SECAO_CNAE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_GRUPO_CNAE
--------------------------------------------------------

  CREATE TABLE "IBGE_GRUPO_CNAE" 
   (	"ID_GRUPO_CNAE" VARCHAR2(200 BYTE), 
	"CODIGO_GRUPO" VARCHAR2(100 BYTE), 
	"DENOMINACAO" VARCHAR2(200 BYTE), 
	"ID_DIVISAO_CNAE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  --------------------------------------------------------
--  DDL for Table IBGE_SECAO_CNAE
--------------------------------------------------------

  CREATE TABLE "IBGE_SECAO_CNAE" 
   (	"ID_SECAO_CNAE" VARCHAR2(200 BYTE), 
	"IDENTIFICADOR_SECAO" VARCHAR2(100 BYTE), 
	"DENOMINACAO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Table IBGE_SUBCLASSE_CNAE
--------------------------------------------------------

  CREATE TABLE "IBGE_SUBCLASSE_CNAE" 
   (	"ID_SUBCLASSE_CNAE" VARCHAR2(300 BYTE), 
	"CODIGO_SUBCLASSE" VARCHAR2(300 BYTE), 
	"DENOMINACAO" VARCHAR2(300 BYTE), 
	"ID_CLASSE_CNAE" VARCHAR2(300 BYTE), 
	"ID_VERSAO" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  --------------------------------------------------------
--  DDL for Table IBGE_VERSAO_CNAE
--------------------------------------------------------

  CREATE TABLE "IBGE_VERSAO_CNAE" 
   (	"ID_VERSAO_CNAE" VARCHAR2(100 BYTE), 
	"NOME_VERSAO" VARCHAR2(100 BYTE), 
	"INICIO_VALIDADE" DATE, 
	"FIM_VALIDADE" DATE, 
	"VERSAO_ANTERIOR" VARCHAR2(100 BYTE), 
	"PROXIMA_VERSAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES_PK" ON "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES" ("ID_ATIVIDADE_ECONOMICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index IBGE_ATIVIDADES_PERMITIDAS_MEI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBGE_ATIVIDADES_PERMITIDAS_MEI_PK" ON "IBGE_ATIVIDADES_PERMITIDAS_MEI" ("ID_ATIVIDADE_ECONOMICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_CLASSE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CLASSE" ON "IBGE_CLASSE_CNAE" ("ID_CLASSE_CNAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_DIVISAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DIVISAO" ON "IBGE_DIVISAO_CNAE" ("ID_DIVISAO_CNAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_GRUPO_CNAE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_GRUPO_CNAE" ON "IBGE_GRUPO_CNAE" ("ID_GRUPO_CNAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
  --------------------------------------------------------
--  DDL for Index PK_SECAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SECAO" ON "IBGE_SECAO_CNAE" ("ID_SECAO_CNAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  DDL for Index PK_SUBCLASSE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SUBCLASSE" ON "IBGE_SUBCLASSE_CNAE" ("ID_SUBCLASSE_CNAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;

  --------------------------------------------------------
--  DDL for Index PK_VERSAO_CNAE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_VERSAO_CNAE" ON "IBGE_VERSAO_CNAE" ("ID_VERSAO_CNAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR" ;
--------------------------------------------------------
--  Constraints for Table IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES
--------------------------------------------------------

  ALTER TABLE "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES" ADD CONSTRAINT "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES_PK" PRIMARY KEY ("ID_ATIVIDADE_ECONOMICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES" MODIFY ("ID_ATIVIDADE_ECONOMICA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_ATIVIDADES_PERMITIDAS_MEI
--------------------------------------------------------

  ALTER TABLE "IBGE_ATIVIDADES_PERMITIDAS_MEI" ADD CONSTRAINT "IBGE_ATIVIDADES_PERMITIDAS_MEI_PK" PRIMARY KEY ("ID_ATIVIDADE_ECONOMICA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_ATIVIDADES_PERMITIDAS_MEI" MODIFY ("ID_ATIVIDADE_ECONOMICA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_CLASSE_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_CLASSE_CNAE" ADD CONSTRAINT "PK_CLASSE" PRIMARY KEY ("ID_CLASSE_CNAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_CLASSE_CNAE" MODIFY ("ID_CLASSE_CNAE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_CLASSE_CNAE" MODIFY ("CODIGO_CLASSE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_CLASSE_CNAE" MODIFY ("DENOMINACAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_CLASSE_CNAE" MODIFY ("ID_GRUPO_CNAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_DIVISAO_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_DIVISAO_CNAE" ADD CONSTRAINT "PK_DIVISAO" PRIMARY KEY ("ID_DIVISAO_CNAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_DIVISAO_CNAE" MODIFY ("ID_DIVISAO_CNAE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_DIVISAO_CNAE" MODIFY ("CODIGO_DIVISAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_DIVISAO_CNAE" MODIFY ("DENOMINACAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_DIVISAO_CNAE" MODIFY ("ID_SECAO_CNAE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_GRUPO_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_GRUPO_CNAE" ADD CONSTRAINT "PK_GRUPO_CNAE" PRIMARY KEY ("ID_GRUPO_CNAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_GRUPO_CNAE" MODIFY ("ID_GRUPO_CNAE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_GRUPO_CNAE" MODIFY ("CODIGO_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_GRUPO_CNAE" MODIFY ("DENOMINACAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_GRUPO_CNAE" MODIFY ("ID_DIVISAO_CNAE" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table IBGE_SECAO_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_SECAO_CNAE" ADD CONSTRAINT "PK_SECAO" PRIMARY KEY ("ID_SECAO_CNAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_SECAO_CNAE" MODIFY ("ID_SECAO_CNAE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_SECAO_CNAE" MODIFY ("IDENTIFICADOR_SECAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_SECAO_CNAE" MODIFY ("DENOMINACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IBGE_SUBCLASSE_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_SUBCLASSE_CNAE" ADD CONSTRAINT "PK_SUBCLASSE" PRIMARY KEY ("ID_SUBCLASSE_CNAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_SUBCLASSE_CNAE" MODIFY ("ID_SUBCLASSE_CNAE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_SUBCLASSE_CNAE" MODIFY ("CODIGO_SUBCLASSE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_SUBCLASSE_CNAE" MODIFY ("DENOMINACAO" NOT NULL ENABLE);
  ALTER TABLE "IBGE_SUBCLASSE_CNAE" MODIFY ("ID_VERSAO" NOT NULL ENABLE);

 --------------------------------------------------------
--  Constraints for Table IBGE_VERSAO_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_VERSAO_CNAE" ADD CONSTRAINT "PK_VERSAO_CNAE" PRIMARY KEY ("ID_VERSAO_CNAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_USR"  ENABLE;
  ALTER TABLE "IBGE_VERSAO_CNAE" MODIFY ("ID_VERSAO_CNAE" NOT NULL ENABLE);
  ALTER TABLE "IBGE_VERSAO_CNAE" MODIFY ("NOME_VERSAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES
--------------------------------------------------------

  ALTER TABLE "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES" ADD CONSTRAINT "IBGE_ATIVIDADES_IMPEDIDAS_SIMPLES_FK1" FOREIGN KEY ("ID_ATIVIDADE_ECONOMICA")
	  REFERENCES "IBGE_SUBCLASSE_CNAE" ("ID_SUBCLASSE_CNAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_ATIVIDADES_PERMITIDAS_MEI
--------------------------------------------------------

  ALTER TABLE "IBGE_ATIVIDADES_PERMITIDAS_MEI" ADD CONSTRAINT "IBGE_ATIVIDADES_PERMITIDAS_MEI_FK1" FOREIGN KEY ("ID_ATIVIDADE_ECONOMICA")
	  REFERENCES "IBGE_SUBCLASSE_CNAE" ("ID_SUBCLASSE_CNAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_CLASSE_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_CLASSE_CNAE" ADD CONSTRAINT "FK_CLASSE_GRUPO" FOREIGN KEY ("ID_GRUPO_CNAE")
	  REFERENCES "IBGE_GRUPO_CNAE" ("ID_GRUPO_CNAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_DIVISAO_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_DIVISAO_CNAE" ADD CONSTRAINT "FK_DIVISAO_SECAO" FOREIGN KEY ("ID_SECAO_CNAE")
	  REFERENCES "IBGE_SECAO_CNAE" ("ID_SECAO_CNAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_GRUPO_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_GRUPO_CNAE" ADD CONSTRAINT "FK_GRUPO_DIVISAO" FOREIGN KEY ("ID_DIVISAO_CNAE")
	  REFERENCES "IBGE_DIVISAO_CNAE" ("ID_DIVISAO_CNAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_SUBCLASSE_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_SUBCLASSE_CNAE" ADD CONSTRAINT "FK_SUBCLASSE_CLASSE" FOREIGN KEY ("ID_CLASSE_CNAE")
	  REFERENCES "IBGE_CLASSE_CNAE" ("ID_CLASSE_CNAE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IBGE_VERSAO_CNAE
--------------------------------------------------------

  ALTER TABLE "IBGE_VERSAO_CNAE" ADD CONSTRAINT "FK_VERSAO_ANTERIOR" FOREIGN KEY ("VERSAO_ANTERIOR")
	  REFERENCES "IBGE_VERSAO_CNAE" ("ID_VERSAO_CNAE") ENABLE;
  ALTER TABLE "IBGE_VERSAO_CNAE" ADD CONSTRAINT "FK_VERSAO_PROXIMA" FOREIGN KEY ("PROXIMA_VERSAO")
	  REFERENCES "IBGE_VERSAO_CNAE" ("ID_VERSAO_CNAE") ENABLE;