-- View Documento_Fiscal
CREATE OR REPLACE VIEW NFE_DOCUMENTO_FISCAL AS
(
    SELECT nfe.ID_INFNFE AS ID_DOCUMENTO,
    ide.ID_IDE,
    cNF AS CODIGO_NUMERICO_CHAVE,
    dhEMI AS DATA_EMISSAO,
    dhEMI AS HORA_EMISSAO,
    dhSaiEnt AS DATA_SAIDA,
    dhSaiEnt AS HORA_SAIDA,
    CHAVE,
    vercProc AS VERSAO,
    cDV AS DIGITO_VERIFICADOR,
    indPag AS FORMA_PAGAMENTO,
    tplmp AS FORMATO_IMPRESSAO,
    tpAmb AS TIPO_AMBIENTE,
    tpEmis AS TIPO_EMISSAO,
    finNFe AS FINALIDADE_EMISSAO,
    indFinal AS CONSUMIDOR_FINAL,
    tpNF AS TIPO_OPERACAO,
    mod AS MODELO,
    serie AS SERIE,
    inf.infAdFisco AS INFORMACOES_ADICIONAIS_FISCO,
    inf.INFCPL AS INFORMACOES_ADICIONAIS_CONTRIBUINTE,
    CRT,
    CNPJ AS EMITENTE,
    idDest AS DESTINATARIO,
    ID_NFref AS NOTA_REFERENCIADA
    FROM APL_NFE.IDE@DL_ARMA ide
    INNER JOIN
    APL_NFE.infNFE@DL_ARMA nfe
    ON
    ide.ID_infNFE = nfe.ID_infNFE
    INNER JOIN
    APL_NFE.nfref@DL_ARMA refs
    ON
    refs.id_ide = ide.ID_ide 
    INNER JOIN
    APL_NFE.emit@DL_ARMA emit
    ON
    nfe.ID_infNFE = emit.ID_infNFE
    INNER JOIN
    APL_NFE.INFADIC@DL_ARMA inf
    ON
    inf.ID_infNFE = nfe.ID_infNFE
) WITH READ ONLY;

-- View Compra
CREATE OR REPLACE VIEW NFE_COMPRA AS
(
    SELECT ID_COMPRA, 
    ID_INFNFE AS DOCUMENTO_FISCAL,
    xPed AS NUMERO_PEDIDO,
    xNEMP AS NOTA_EMPENHO,
    xCont AS CONTRATO
    FROM APL_NFE.COMPRA@DL_ARMA 
)
WITH READ ONLY;

-- View Avulsa
CREATE OR REPLACE VIEW NFE_NF_AVULSA AS
(
    SELECT 
    ID_avulsa AS ID_AVULSA,
    avulsa.ID_infNFE AS DOCUMENTO_FISCAL,
    repEmi AS REPARTICAO_FISCAL,
    emit.CNPJ AS REMETENTE,
    matr AS AGENTE_FISCO,
    nDAR AS DOCUMENTO_ARRECADACAO
    FROM APL_NFE.AVULSA@DL_ARMA avulsa
    INNER JOIN
    APL_NFE.EMIT@DL_ARMA emit
    ON
    avulsa.ID_infNFE = emit.ID_infNFE
)
WITH READ ONLY;

-- View Documento Arrecadacao
CREATE OR REPLACE VIEW NFE_DOCUMENTO_ARRECADACAO AS
(
    SELECT NDAR AS NUMERO,
    dEmi AS DATA_EMISSAO,
    vDAR AS VALOR_TOTAL,
    dPag AS DATA_PAGAMENTO 
    FROM APL_NFE.AVULSA@DL_ARMA
)
WITH READ ONLY;

-- View NFE
CREATE OR REPLACE VIEW NFE_NFE AS
(
    SELECT nfe.ID_INFNFE AS ID_DOCUMENTO,
    ide.ID_IDE,
    cNF AS CODIGO_NUMERICO_CHAVE,
    dhEMI AS DATA_EMISSAO,
    dhEMI AS HORA_EMISSAO,
    dhSaiEnt AS DATA_SAIDA,
    dhSaiEnt AS HORA_SAIDA,
    CHAVE,
    vercProc AS VERSAO,
    cDV AS DIGITO_VERIFICADOR,
    indPag AS FORMA_PAGAMENTO,
    tplmp AS FORMATO_IMPRESSAO,
    tpAmb AS TIPO_AMBIENTE,
    tpEmis AS TIPO_EMISSAO,
    finNFe AS FINALIDADE_EMISSAO,
    indFinal AS CONSUMIDOR_FINAL,
    tpNF AS TIPO_OPERACAO,
    mod AS MODELO,
    serie AS SERIE,
    inf.infAdFisco AS INFORMACOES_ADICIONAIS_FISCO,
    inf.INFCPL AS INFORMACOES_ADICIONAIS_CONTRIBUINTE,
    CRT,
    CNPJ AS EMITENTE,
    idDest AS DESTINATARIO,
    ID_NFref AS NOTA_REFERENCIADA
    FROM APL_NFE.IDE@DL_ARMA ide
    INNER JOIN
    APL_NFE.infNFE@DL_ARMA nfe
    ON
    ide.ID_infNFE = nfe.ID_infNFE
    INNER JOIN
    APL_NFE.nfref@DL_ARMA refs
    ON
    refs.id_ide = ide.ID_ide 
    INNER JOIN
    APL_NFE.emit@DL_ARMA emit
    ON
    nfe.ID_infNFE = emit.ID_infNFE
    INNER JOIN
    APL_NFE.INFADIC@DL_ARMA inf
    ON
    inf.ID_infNFE = nfe.ID_infNFE
)
WITH READ ONLY;

-- View Destinatario
CREATE OR REPLACE VIEW NFE_DESTINATARIO_NF AS
(
    SELECT DISTINCT CONCAT(CNPJ, CPF) AS CNPJ_CPF,
    xNome AS NOME,
    IE2 AS INSCRICAO_ESTADUAL,
    IndlEDest AS INDICADOR_INSCRICAO_ESTADUAL,
    ISUF AS INSCRICAO_SUFRAMA,
    IM AS INSCRICAO_MUNICIPAL,
    email AS EMAIL,
    idEstrangeiro AS ESTRANGEIRO
    FROM APL_NFE.DEST@DL_ARMA
)
WITH READ ONLY;

-- View Emitente
CREATE OR REPLACE VIEW NFE_EMITENTE_NF AS
(
    SELECT DISTINCT CNPJ,
    XNOME AS NOME_RAZAO,
    IE2 AS INSCRICAO_ESTADUAL,
    IM AS INSCRICAO_MUNICIPAL,
    IEST2 AS INSCRICAO_ESTADUAL_ST_NUMERICA,
    CNAE 
    FROM APL_NFE.EMIT@DL_ARMA
)
WITH READ ONLY;

-- View Estabelecimento
CREATE OR REPLACE VIEW NFE_ESTABELECIMENTO AS
(
    SELECT DISTINCT CNPJ,
    XNOME AS RAZAO_SOCIAL,
    XFant AS NOME_FANTASIA
    FROM APL_NFE.EMIT@DL_ARMA
    UNION ALL
    SELECT CNPJ,
    xNome AS RAZAO_SOCIAL,
    '' AS NOME_FANTASIA
	FROM APL_NFE.DEST@DL_ARMA
)
WITH READ ONLY;

-- View Pessoa
CREATE OR REPLACE VIEW NFE_PESSOA AS
(
    SELECT DISTINCT CPF,
    XNOME AS NOME
    FROM APL_NFE.EMIT@DL_ARMA
    UNION ALL
    SELECT DISTINCT CPF,
    xNome AS NOME
	FROM APL_NFE.DEST@DL_ARMA
)
WITH READ ONLY;

-- View Atividade Econômica
CREATE OR REPLACE VIEW NFE_ATIVIDADE_ECONOMICA AS
(
    SELECT DISTINCT CNAE
    FROM APL_NFE.EMIT@DL_ARMA
)
WITH READ ONLY;

-- View Remetente
CREATE OR REPLACE VIEW NFE_REMETENTE_NF AS
(
    SELECT DISTINCT CPF,
    XNome AS NOME 
    FROM APL_NFE.EMIT@DL_ARMA
)
WITH READ ONLY;

-- View Entrega
CREATE OR REPLACE VIEW NFE_ENTREGA AS
(
    SELECT ID_ENTREGA,
    ID_infNFE AS DOCUMENTO_FISCAL,
    ID_ENTREGA AS ENDERECO,
    FONE AS TELEFONE,
    EMAIL
    FROM APL_NFE.ENTREGA@DL_ARMA
)
WITH READ ONLY;

-- View Retirada
CREATE OR REPLACE VIEW NFE_RETIRADA AS
(
    SELECT ID_RETIRADA,
    ID_infNFE AS DOCUMENTO_FISCAL,
    ID_RETIRADA AS ENDERECO,
    FONE AS TELEFONE,
    EMAIL
    FROM APL_NFE.RETIRADA@DL_ARMA
)
WITH READ ONLY;

-- View de Endereco
CREATE OR REPLACE VIEW NFE_ENDERECO AS
(
		SELECT CONCAT(CNPJ,CPF) AS ID,
        xMun AS CIDADE,
        UF AS ESTADO,
        xBairro AS BAIRRO,
        xLgr AS LOGRADOURO,
        CEP,
        nro AS NUMERO,
        xClp AS COMPLEMENTO,
        xPais AS PAIS,
        ID_ENTREGA AS CODIGO_ENDERECO, 
        CONCAT(CNPJ,CPF) AS CNPJ_CPF,
        TO_CHAR(IE) AS IE,
        'ENTREGA' AS TIPO
        FROM APL_NFE.ENTREGA@DL_ARMA entr
        UNION ALL
        SELECT CONCAT(CNPJ,CPF) AS ID,
        xMun AS CIDADE,
        UF AS ESTADO,
        xBairro AS BAIRRO,
        xLgr AS LOGRADOURO,
        CEP,
        nro AS NUMERO,
        xClp AS COMPLEMENTO,
        xPais AS PAIS,
        ID_RETIRADA AS CODIGO_ENDERECO, 
        CONCAT(CNPJ,CPF) AS CNPJ_CPF,
        TO_CHAR(IE) AS IE,
        'RETIRADA' AS TIPO
        FROM APL_NFE.RETIRADA@DL_ARMA
        UNION ALL
        SELECT  CONCAT(dest.CNPJ,dest.CPF) AS ID,
        xMun AS CIDADE,
        UF AS ESTADO,
        xBairro AS BAIRRO,
        xLgr AS LOGRADOURO,
        CEP,
        nro AS NUMERO,
        xCPL AS COMPLEMENTO,
        xPais AS PAIS,
        dest.ID_DEST AS CODIGO_ENDERECO, 
        CONCAT(dest.CNPJ,dest.CPF) AS CNPJ_CPF,
        TO_CHAR(dest.IE2) AS IE,
        'DESTINATARIO' AS TIPO
        FROM APL_NFE.enderdest@DL_ARMA enddest
        INNER JOIN
        APL_NFE.dest@DL_ARMA dest
        ON
        dest.ID_DEST = enddest.ID_DEST
)
WITH READ ONLY;

-- View Transportador
CREATE OR REPLACE VIEW NFE_TRANSPORTADOR AS
(
    SELECT DISTINCT ID_TRANSPORTA, 
    IE AS INSCRICAO_ESTADUAL,
    CONCAT(CNPJ,CPF) AS CNPJ_CPF
    FROM APL_NFE.TRANSPORTA@DL_ARMA
)
WITH READ ONLY;

-- View Informações Adicionais Fisco
CREATE OR REPLACE VIEW NFE_INFORMACOES_ADICIONAIS_FISCO AS
(
    SELECT ID_INFNFE AS ID, 
    infCpl AS DESCRICAO,
    xCampo AS CAMPO,
    xTexto AS TEXTO,
    ID_obsFisco AS OBS_FISCO
    FROM APL_NFE.INFADIC@DL_ARMA infadic
    INNER JOIN
    APL_NFE.OBSFISCO@DL_ARMA fisco
    ON
    infadic.ID_INFADIC = fisco.ID_infAdic
)
WITH READ ONLY;

-- View Informações Adicionais Contribuinte
CREATE OR REPLACE VIEW NFE_INFORMACOES_ADICIONAIS_CONTRIBUINTE AS
(
    SELECT ID_INFNFE AS ID, 
    infCpl AS DESCRICAO,
    xCampo AS CAMPO,
    xTexto AS TEXTO,
    ID_obsCont AS OBS_CONTRIBUINTE
    FROM APL_NFE.INFADIC@DL_ARMA infadic
    INNER JOIN
    APL_NFE.OBSCONT@DL_ARMA cont
    ON
    infadic.ID_INFADIC = cont.ID_infAdic
)
WITH READ ONLY;

-- View Modalidade Frete
CREATE OR REPLACE VIEW NFE_MODALIDADE_FRETE AS
(
    SELECT ID_transp as CODIGO_MODALIDADE,
    modFrete AS MODALIDADE,
    VAGAO,
    BALSA
    FROM APL_NFE.TRANSP@DL_ARMA
)
WITH READ ONLY;

-- View Estrangeiro
CREATE OR REPLACE VIEW NFE_ESTRANGEIRO AS
(
    SELECT DISTINCT CONCAT(CNPJ,CPF) AS CNPJ_CPF,
    EMAIL  
    FROM APL_NFE.DEST@DL_ARMA
)
WITH READ ONLY;

-- View Documento Referenciado
CREATE OR REPLACE VIEW NFE_DOCUMENTO_REFERENCIADO AS
(
    SELECT refNFe AS CODIGO,
    mod AS MODELO 
    FROM APL_NFE.NFREF@DL_ARMA ref
    INNER JOIN
    APL_NFE.IDE@DL_ARMA ide
    ON
    ide.ID_ide = ref.ID_ide
)
WITH READ ONLY;

-- View Produtor Rural
CREATE OR REPLACE VIEW NFE_PRODUTOR_RURAL AS
(
    SELECT ID_REFNFP AS ID,
    ID_IDE,
    MOD AS MODELO,
    refCTe AS CHAVE_ACESSO_CTE
    FROM APL_NFE.refNFP@DL_ARMA
)
WITH READ ONLY;

-- View NF Referenciada
CREATE OR REPLACE VIEW NFE_NF_REFERENCIADA AS
(
    SELECT ID_refECF AS ID,
    ID_IDE,
    MOD AS MODELO,
    nECF AS NUMERO_ECF
    FROM APL_NFE.refECF@DL_ARMA
)
WITH READ ONLY;

-- View NF Cupom Fiscal
CREATE OR REPLACE VIEW NFE_CUPOM_FISCAL AS
(
    SELECT ID_refECF AS ID,
    ID_IDE,
    MOD AS MODELO,
    nECF AS NUMERO_ECF
    FROM APL_NFE.refECF@DL_ARMA
)
WITH READ ONLY;

-- View Item
CREATE OR REPLACE VIEW NFE_ITEM AS
(
    SELECT ID_PROD AS ID_ITEM,
    ID_compra AS COMPRA,
    cProd AS NUMERO,
    indTot AS INDICADOR_VALOR_TOTAL,
    INFADPROD AS INFORMACOES_ADICIONAIS,
    qTrib AS QUANTIDADE_TRIBUTAVEL,
    CFOP,
    CEST,
    vUnTrib AS VALOR_UNITARIO_TRIBUTACAO,
    vUnCom AS VALOR_UNITARIO,
    qCom AS QUANTIDADE_COMERCIAL,
    uCom AS UNIDADE_COMERCIAL,
    NCM AS CODIGO_NCM,
    cEANTrib AS CEAN_TRIB,
    cEAN AS CEAN,
    xProd AS DESCRICAO,
    vFrete AS VALOR_TOTAL_FRETE,
    vSeg AS VALOR_SEGURO,
    vDesc AS VALOR_DESCONTO,
    vOutro AS OUTRAS_DESPESAS
    FROM APL_NFE.PROD@DL_ARMA prod
    INNER JOIN
    APL_NFE.DET@DL_ARMA det
    ON
    det.ID_det = prod.ID_det
    INNER JOIN
    APL_NFE.COMPRA@DL_ARMA 
    ON 
    det.ID_INFNFE = compra.ID_INFNFE 
    UNION
    SELECT ID_PROD AS ID_ITEM,
    ID_compra AS COMPRA,
    cProd AS NUMERO,
    indTot AS INDICADOR_VALOR_TOTAL,
    INFADPROD AS INFORMACOES_ADICIONAIS,
    qTrib AS QUANTIDADE_TRIBUTAVEL,
    CFOP,
    CEST,
    vUnTrib AS VALOR_UNITARIO_TRIBUTACAO,
    vUnCom AS VALOR_UNITARIO,
    qCom AS QUANTIDADE_COMERCIAL,
    uCom AS UNIDADE_COMERCIAL,
    NCM AS CODIGO_NCM,
    cEANTrib AS CEAN_TRIB,
    cEAN AS CEAN,
    xProd AS DESCRICAO,
    vFrete AS VALOR_TOTAL_FRETE,
    vSeg AS VALOR_SEGURO,
    vDesc AS VALOR_DESCONTO,
    vOutro AS OUTRAS_DESPESAS
	FROM APL_NFE.PROD@DL_ARMA prod
    INNER JOIN
    APL_NFE.DET@DL_ARMA det
    ON
    det.ID_det = prod.ID_det
    INNER JOIN
    APL_NFE.COMPRA@DL_ARMA 
    ON 
    det.ID_INFNFE = compra.ID_INFNFE 
)
WITH READ ONLY;

-- View Produto
CREATE OR REPLACE VIEW NFE_Produto AS
(
    SELECT ID_PROD AS ID_PRODUTO,
    cProd AS NUMERO,
    indTot AS INDICADOR_VALOR_TOTAL,
    INFADPROD AS INFORMACOES_ADICIONAIS,
    qTrib AS QUANTIDADE_TRIBUTAVEL,
    CFOP,
    CEST,
    vUnTrib AS VALOR_UNITARIO_TRIBUTACAO,
    vUnCom AS VALOR_UNITARIO,
    qCom AS QUANTIDADE_COMERCIAL,
    uCom AS UNIDADE_COMERCIAL,
    NCM AS CODIGO_NCM,
    cEANTrib AS CEAN_TRIB,
    cEAN AS CEAN,
    xProd AS DESCRICAO,
    vFrete AS VALOR_TOTAL_FRETE,
    vSeg AS VALOR_SEGURO,
    vDesc AS VALOR_DESCONTO,
    vOutro AS OUTRAS_DESPESAS
    FROM APL_NFE.PROD@DL_ARMA prod
    INNER JOIN
    APL_NFE.DET@DL_ARMA det
    ON
    det.ID_det = prod.ID_det
)
WITH READ ONLY;

-- View Serviço
CREATE OR REPLACE VIEW NFE_Servico AS
(
    SELECT ID_PROD AS ID_PRODUTO,
    cProd AS NUMERO,
    indTot AS INDICADOR_VALOR_TOTAL,
    INFADPROD AS INFORMACOES_ADICIONAIS,
    qTrib AS QUANTIDADE_TRIBUTAVEL,
    CFOP,
    CEST,
    vUnTrib AS VALOR_UNITARIO_TRIBUTACAO,
    vUnCom AS VALOR_UNITARIO,
    qCom AS QUANTIDADE_COMERCIAL,
    uCom AS UNIDADE_COMERCIAL,
    NCM AS CODIGO_NCM,
    cEANTrib AS CEAN_TRIB,
    cEAN AS CEAN,
    xProd AS DESCRICAO,
    vFrete AS VALOR_TOTAL_FRETE,
    vSeg AS VALOR_SEGURO,
    vDesc AS VALOR_DESCONTO,
    vOutro AS OUTRAS_DESPESAS
    FROM APL_NFE.PROD@DL_ARMA prod
    INNER JOIN
    APL_NFE.DET@DL_ARMA det
    ON
    det.ID_det = prod.ID_det
)
WITH READ ONLY;

-- View Imposto Normal
CREATE OR REPLACE VIEW NFE_IMPOSTO_NORMAL AS
(
    SELECT ID_IMPOSTO,
    orig AS ORIGEM
    FROM APL_NFE.ICMS@DL_ARMA
)
WITH READ ONLY;

-- View Imposto ICMS Diferimento
CREATE OR REPLACE VIEW NFE_IMPOSTO_DIFERIMENTO AS
(
    SELECT ID_IMPOSTO,
    orig AS ORIGEM,
    CST,
    modBC AS MODALIDADE_BC,
    pRedBC AS PERCENTUAL_REDUCAO_BASE_CALCULO,
    vBC AS VALOR_BASE_CALCULO,
    pICMS AS ALIQUOTA,
    vICMSOp AS VALOR_ICMS_OPERACAO,
    pDif AS PERCENTUAL_DIFERIMENTO,
    vICMSDif AS VALOR_ICMS_DIFERIDO,
    vICMS AS VALOR_ICMS,
    vBCFCP AS VALOR_BASE_CALCULO_FCP,
    pFCP AS PERCENTUAL_FCP,
    vFCP AS VALOR_FCP
    FROM APL_NFE.ICMS51@DL_ARMA
)
WITH READ ONLY;

-- View Imposto ICMS Não Tributada Suspensa
CREATE OR REPLACE VIEW NFE_NAO_TRIBUTADA_SUSPENSA AS
(
    SELECT ID_IMPOSTO,
    orig AS ORIGEM,
    CST,
    vICMSDeson AS VALOR_ICMS,
    motDesICMS AS MOTIVO_DESONERACAO
    FROM APL_NFE.ICMS30@DL_ARMA
)
WITH READ ONLY;

-- View Imposto ICMS Redução BC
CREATE OR REPLACE VIEW NFE_IMPOSTO_REDUCAO_BC AS
(
    SELECT ID_IMPOSTO,
    orig AS ORIGEM,
    CST,
    modBC AS MODALIDADE_BC,
    pRedBC AS PERCENTUAL_REDUCAO_BASE_CALCULO,
    vBC AS VALOR_BASE_CALCULO,
    pICMS AS ALIQUOTA,
    vICMS AS VALOR_ICMS,
    vBCFCP AS VALOR_BASE_CALCULO_FCP,
    pFCP AS PERCENTUAL_FCP,
    vFCP AS VALOR_FCP,
    modBCST AS MODALIDADE_BC_ICMS_ST,
    pMVAST AS PERCENTUAL_MARGEM_VALOR_ICMS_ST,
    pRedBCST AS PERCENTUAL_REDUCAO_BC_ICMS_ST,
    vICMSST AS VALOR_ICMS_ST,
    vBCFCPST AS VALOR_BC_FCP_ST,
    pFCPST AS PERCENTUAL_FCP_ST,
    vFCPST AS VALOR_FCP_ST,
    vICMSDeson AS VALOR_ICMS_DESONERADO,
    motDesICMS AS MOTIVO_DESONERACAO
    FROM APL_NFE.ICMS70@DL_ARMA
)
WITH READ ONLY;

-- View Imposto Integral
CREATE OR REPLACE VIEW NFE_IMPOSTO_INTEGRAL AS
(
    SELECT ID_IMPOSTO,
    orig AS ORIGEM,
    CST,
    modBC AS MODALIDADE_BC,
    vBC AS VALOR_BASE_CALCULO,
    pICMS AS ALIQUOTA,
    vICMS AS VALOR_ICMS,
    pFCP AS PERCENTUAL_FCP,
    vFCP AS VALOR_FCP
    FROM APL_NFE.ICMS00@DL_ARMA
)
WITH READ ONLY;

-- View Imposto Outros
CREATE OR REPLACE VIEW NFE_IMPOSTO_OUTROS AS
(
    SELECT ID_IMPOSTO,
    orig AS ORIGEM,
    CST,
    modBC AS MODALIDADE_BC,
    vBC AS VALOR_BASE_CALCULO,
    pRedBC AS PERCENTUAL_REDUCAO_BASE_CALCULO,
    pICMS AS ALIQUOTA,
    vICMS AS VALOR_ICMS,
    vBCFCP AS VALOR_BASE_CALCULO_FCP,
    pFCP AS PERCENTUAL_FCP,
    vFCP AS VALOR_FCP,
    modBCST AS MODALIDADE_BC_ICMS_ST,
    pMVAST AS PERCENTUAL_MARGEM_VALOR_ICMS_ST,
    pRedBCST AS PERCENTUAL_REDUCAO_BC_ICMS_ST,
    vBCST AS VALOR_BC_ST,
    pICMSST AS ALIQUOTA_ICMS_ST,
    vICMSST AS VALOR_ICMS_ST,
    vBCFCPST AS VALOR_BC_FCP_ST,
    pFCPST AS PERCENTUAL_FCP_ST,
    vFCPST AS VALOR_FCP_ST,
    vICMSDeson AS VALOR_ICMS_DESONERADO,
    motDesICMS AS MOTIVO_DESONERACAO
    FROM APL_NFE.ICMS90@DL_ARMA
)
WITH READ ONLY;

-- View Imposto Simples Nacional Anteriormente ST
CREATE OR REPLACE VIEW NFE_IMPOSTO_SIMPLES_NACIONAL_ANTERIORMENTE_ST AS
(
    SELECT ID_IMPOSTO,
    orig AS ORIGEM,
    CST,
    vBCSTRet AS VALOR_BC_ICMS_ST,
    pST AS ALIQUOTA_CONSUMIDOR_FINAL,
    vICMSSubstituto AS VALOR_ICMS_ST,
    vICMSSTRet AS VALOR_ICMS_RETIDO,
    vBCFCPSTRet AS VALOR_BC_FCP_RETIDO,
    pFCPSTRet AS PERCENTUAL_FCP_RETIDO_ST,
    vFCPSTRet AS VALOR_FCP_RETIDO_ST,
    vBCSTDest AS VALOR_BC_ICMS_ST_UF_DESTINO,
    vICMSSTDest AS VALOR_ICMS_ST_UF_DESTINO,
    pRedBCEfet AS PERCENTUAL_REDUCAO_BC,
    vBCEfet AS VALOR_BC_EFETIVA,
    pICMSEfet AS ALIQUOTA_ICMS_EFETIVA,
    vICMSEfet AS VALOR_ICMS_EFETIVO
    FROM APL_NFE.ICMSST@DL_ARMA
)
WITH READ ONLY;