
  CREATE TABLE "UFC_SEM"."SAMEAS_CAD_REDESIM_PESSOA" 
   (	"CAD_ID" NUMBER(14,0) NOT NULL ENABLE, 
	"REDESIM_ID" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;

  CREATE INDEX "UFC_SEM"."SAMEAS_CAD_REDESIM_PESSOA_INDEX1" ON "UFC_SEM"."SAMEAS_CAD_REDESIM_PESSOA" ("CAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;

  CREATE INDEX "UFC_SEM"."SAMEAS_CAD_REDESIM_PESSOA_INDEX2" ON "UFC_SEM"."SAMEAS_CAD_REDESIM_PESSOA" ("REDESIM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_D_UFC_SEM" ;
